import { Lesson } from './types'

export const A1_LESSONS_7_TO_30: Lesson[] = [
  {
    id: 'a1-7',
    level: 'A1',
    order: 7,
    title: 'La Familia (Posesivos)',
    objective: 'Usar pronombres y adjetivos posesivos para hablar de la familia',
    vocabulary: [
      { word: 'Family', translation: 'Familia', example: 'My family is big.', type: 'noun' },
      { word: 'Parent', translation: 'Padre/Madre', example: 'My parents are doctors.', type: 'noun' },
      { word: 'Child', translation: 'Niño/a', example: 'They have two children.', type: 'noun' },
      { word: 'Grandmother', translation: 'Abuela', example: 'My grandmother is 80.', type: 'noun' },
      { word: 'Grandfather', translation: 'Abuelo', example: 'His grandfather lives in Spain.', type: 'noun' },
    ],
    grammar: {
      title: 'Pronombres y Adjetivos Posesivos',
      explanation: 'Los adjetivos posesivos (my, your, his, her, our, their) indican pertenencia.',
      examples: ['This is my family.', 'Her mother is a teacher.', 'Our house is big.'],
      rules: ['My/your/his/her + sustantivo', 'Our/their + sustantivo', 'No cambian en plural'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'This is ___ sister.', options: ['I', 'my', 'me', 'mine'], correctAnswer: 'my', explanation: 'Usamos "my" antes del sustantivo.' },
      { id: 'ex2', type: 'fill-blank', question: '___ parents are kind.', correctAnswer: 'Their', explanation: 'Usamos "their" para posesión de ellos.' },
    ],
    shadowingText: 'This is my family. My mother is Maria. My father is John. I have one sister. Her name is Anna.',
  },
  {
    id: 'a1-8',
    level: 'A1',
    order: 8,
    title: 'Números, Precios y Teléfonos',
    objective: 'Usar números del 0 al 100 en contextos prácticos',
    vocabulary: [
      { word: 'Number', translation: 'Número', example: 'What is your phone number?', type: 'noun' },
      { word: 'Phone', translation: 'Teléfono', example: 'My phone is new.', type: 'noun' },
      { word: 'Cost', translation: 'Costo', example: 'How much does it cost?', type: 'verb' },
      { word: 'Dollar', translation: 'Dólar', example: 'It costs ten dollars.', type: 'noun' },
      { word: 'Fifty', translation: 'Cincuenta', example: 'I have fifty pesos.', type: 'noun' },
    ],
    grammar: {
      title: 'Números 0-100',
      explanation: 'Los números se usan para precios, teléfonos y cantidades.',
      examples: ['It costs twenty dollars.', 'My number is 555-1234.', 'I am thirty years old.'],
      rules: ['13-19 terminan en -teen', '20, 30, 40... terminan en -ty', 'How much...? para precios'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'What comes after nineteen?', options: ['Eighteen', 'Twenty', 'Thirty', 'Twelve'], correctAnswer: 'Twenty', explanation: 'Veinte viene después de diecinueve.' },
      { id: 'ex2', type: 'fill-blank', question: 'The book costs ___ dollars. (15)', correctAnswer: 'fifteen', explanation: 'Fifteen es 15 en inglés.' },
    ],
    shadowingText: 'My phone number is five five five, one two three four. The shirt costs twenty-five dollars. I need fifty pesos.',
  },
  {
    id: 'a1-9',
    level: 'A1',
    order: 9,
    title: 'Adjetivos: Colores y Tamaño',
    objective: 'Describir personas y cosas usando adjetivos',
    vocabulary: [
      { word: 'Big', translation: 'Grande', example: 'This is a big house.', type: 'adjective' },
      { word: 'Small', translation: 'Pequeño', example: 'I have a small dog.', type: 'adjective' },
      { word: 'Green', translation: 'Verde', example: 'The grass is green.', type: 'adjective' },
      { word: 'Yellow', translation: 'Amarillo', example: 'The sun is yellow.', type: 'adjective' },
      { word: 'Beautiful', translation: 'Hermoso', example: 'She is beautiful.', type: 'adjective' },
    ],
    grammar: {
      title: 'Orden de los Adjetivos',
      explanation: 'Los adjetivos van antes del sustantivo en inglés.',
      examples: ['A red car', 'A big house', 'A beautiful day', 'Small blue eyes'],
      rules: ['Adjetivo + sustantivo', 'Varios adjetivos: opinión + tamaño + color', 'Be + adjetivo para describir'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'She has ___ hair.', options: ['long beautiful', 'beautiful long', 'beautifully long', 'long beauty'], correctAnswer: 'beautiful long', explanation: 'Opinión antes de descripción física.' },
      { id: 'ex2', type: 'fill-blank', question: 'The sky is ___.', correctAnswer: 'blue', explanation: 'El cielo es azul.' },
    ],
    shadowingText: 'I have a big red car. My house is small but beautiful. She has long black hair. The flowers are yellow and white.',
  },
  {
    id: 'a1-10',
    level: 'A1',
    order: 10,
    title: 'Demostrativos (This/That/These/Those)',
    objective: 'Indicar la ubicación de objetos usando demostrativos',
    vocabulary: [
      { word: 'This', translation: 'Este/Esta', example: 'This is my book.', type: 'phrase' },
      { word: 'That', translation: 'Ese/Esa', example: 'That is your chair.', type: 'phrase' },
      { word: 'These', translation: 'Estos/Estas', example: 'These are my keys.', type: 'phrase' },
      { word: 'Those', translation: 'Esos/Esas', example: 'Those are your pens.', type: 'phrase' },
      { word: 'Here', translation: 'Aquí', example: 'Come here!', type: 'adverb' },
    ],
    grammar: {
      title: 'Demostrativos',
      explanation: 'This/that para singular, these/those para plural. This/these para cerca, that/those para lejos.',
      examples: ['This book is mine.', 'That car is red.', 'These shoes are new.', 'Those buildings are tall.'],
      rules: ['This/these = cerca', 'That/those = lejos', 'Singular vs plural'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: '___ is my bag. (near)', options: ['This', 'That', 'These', 'Those'], correctAnswer: 'This', explanation: 'This para singular cercano.' },
      { id: 'ex2', type: 'fill-blank', question: '___ books are interesting. (far, plural)', correctAnswer: 'Those', explanation: 'Those para plural lejano.' },
    ],
    shadowingText: 'This is my phone. That is your computer. These are my books. Those are your pencils. Come here, please!',
  },
  {
    id: 'a1-11',
    level: 'A1',
    order: 11,
    title: 'Have got / Has got (Posesiones)',
    objective: 'Expresar posesión con have/has got',
    vocabulary: [
      { word: 'Have', translation: 'Tener', example: 'I have a car.', type: 'verb' },
      { word: 'Pet', translation: 'Mascota', example: 'She has a pet dog.', type: 'noun' },
      { word: 'Bicycle', translation: 'Bicicleta', example: 'I have got a bicycle.', type: 'noun' },
      { word: 'Laptop', translation: 'Laptop', example: 'He has a laptop.', type: 'noun' },
      { word: 'Own', translation: 'Poseer', example: 'I own a house.', type: 'verb' },
    ],
    grammar: {
      title: 'Have got / Has got',
      explanation: 'Usamos have/has got para expresar posesión (más común en inglés británico).',
      examples: ['I have got a dog.', 'She has got two brothers.', 'They have got a big house.'],
      rules: ['I/You/We/They have got', 'He/She/It has got', 'También: I have, She has (sin got)'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'She ___ a beautiful garden.', options: ['have', 'has', 'have got', 'having'], correctAnswer: 'has', explanation: 'Con she usamos has.' },
      { id: 'ex2', type: 'fill-blank', question: 'I ___ got three cats.', correctAnswer: 'have', explanation: 'Con I usamos have.' },
    ],
    shadowingText: 'I have got a dog and a cat. She has got two sisters. We have got a nice house. They have got many friends.',
  },
  {
    id: 'a1-12',
    level: 'A1',
    order: 12,
    title: 'Presente Simple: Afirmativo (Rutinas)',
    objective: 'Describir rutinas y actividades diarias',
    vocabulary: [
      { word: 'Wake up', translation: 'Despertar', example: 'I wake up at 7 AM.', type: 'verb' },
      { word: 'Breakfast', translation: 'Desayuno', example: 'I eat breakfast every day.', type: 'noun' },
      { word: 'Go', translation: 'Ir', example: 'I go to work.', type: 'verb' },
      { word: 'Watch', translation: 'Ver', example: 'I watch TV.', type: 'verb' },
      { word: 'Every day', translation: 'Todos los días', example: 'I study every day.', type: 'phrase' },
    ],
    grammar: {
      title: 'Presente Simple - Afirmativo',
      explanation: 'Usamos el presente simple para rutinas y hábitos.',
      examples: ['I work every day.', 'She studies English.', 'We live in Madrid.', 'They play soccer.'],
      rules: ['I/You/We/They + verbo base', 'He/She/It + verbo + s', 'Verbos que terminan en -y: estudies'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'She ___ to school every day.', options: ['go', 'goes', 'going', 'gos'], correctAnswer: 'goes', explanation: 'Con she agregamos -es a go.' },
      { id: 'ex2', type: 'fill-blank', question: 'I ___ breakfast at 8 AM.', correctAnswer: 'eat', explanation: 'Con I usamos el verbo base.' },
    ],
    shadowingText: 'Every day, I wake up at seven. I eat breakfast. I go to work at eight. In the evening, I watch TV and study English.',
  },
  {
    id: 'a1-13',
    level: 'A1',
    order: 13,
    title: 'Tercera Persona Singular (-s)',
    objective: 'Dominar la -s de tercera persona en presente simple',
    vocabulary: [
      { word: 'Works', translation: 'Trabaja', example: 'He works at a bank.', type: 'verb' },
      { word: 'Lives', translation: 'Vive', example: 'She lives in London.', type: 'verb' },
      { word: 'Teaches', translation: 'Enseña', example: 'My mother teaches math.', type: 'verb' },
      { word: 'Washes', translation: 'Lava', example: 'He washes his car.', type: 'verb' },
      { word: 'Flies', translation: 'Vuela', example: 'The bird flies high.', type: 'verb' },
    ],
    grammar: {
      title: 'Tercera Persona Singular',
      explanation: 'En presente simple, he/she/it requiere -s, -es, o -ies al final del verbo.',
      examples: ['She works here.', 'He watches TV.', 'It flies fast.', 'My sister studies hard.'],
      rules: ['Verbos normales + s', 'Verbos en -ch, -sh, -s, -x, -o + es', 'Verbos en consonante+y → ies'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'My brother ___ English.', options: ['study', 'studys', 'studies', 'studying'], correctAnswer: 'studies', explanation: 'Study cambia a studies.' },
      { id: 'ex2', type: 'fill-blank', question: 'She ___ at a hospital. (work)', correctAnswer: 'works', explanation: 'Work + s = works.' },
    ],
    shadowingText: 'My father works at a bank. My mother teaches English. My brother studies medicine. My sister lives in Paris.',
  },
  {
    id: 'a1-14',
    level: 'A1',
    order: 14,
    title: 'Presente Simple: Negativo',
    objective: 'Expresar lo que no haces habitualmente',
    vocabulary: [
      { word: 'Don\'t', translation: 'No (hacer)', example: 'I don\'t like coffee.', type: 'phrase' },
      { word: 'Doesn\'t', translation: 'No (hace)', example: 'She doesn\'t work here.', type: 'phrase' },
      { word: 'Never', translation: 'Nunca', example: 'I never smoke.', type: 'adverb' },
      { word: 'Smoke', translation: 'Fumar', example: 'I don\'t smoke.', type: 'verb' },
      { word: 'Drink', translation: 'Beber', example: 'He doesn\'t drink alcohol.', type: 'verb' },
    ],
    grammar: {
      title: 'Presente Simple - Negativo',
      explanation: 'Usamos don\'t/doesn\'t + verbo base para negar en presente simple.',
      examples: ['I don\'t work on Sundays.', 'She doesn\'t like pizza.', 'We don\'t live here.'],
      rules: ['I/You/We/They + don\'t + verbo base', 'He/She/It + doesn\'t + verbo base', 'El verbo NO lleva -s'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'He ___ coffee.', options: ['don\'t drink', 'doesn\'t drink', 'doesn\'t drinks', 'not drink'], correctAnswer: 'doesn\'t drink', explanation: 'Con he usamos doesn\'t + verbo base.' },
      { id: 'ex2', type: 'fill-blank', question: 'I ___ like cold weather.', correctAnswer: 'don\'t', explanation: 'Con I usamos don\'t.' },
    ],
    shadowingText: 'I don\'t like coffee. She doesn\'t work on weekends. We don\'t live in the city. They don\'t speak Spanish.',
  },
  {
    id: 'a1-15',
    level: 'A1',
    order: 15,
    title: 'Presente Simple: Preguntas',
    objective: 'Hacer preguntas sobre hábitos',
    vocabulary: [
      { word: 'Do', translation: 'Hacer (auxiliar)', example: 'Do you like music?', type: 'verb' },
      { word: 'Does', translation: 'Hace (auxiliar)', example: 'Does she work here?', type: 'verb' },
      { word: 'Often', translation: 'A menudo', example: 'Do you often travel?', type: 'adverb' },
      { word: 'Usually', translation: 'Usualmente', example: 'Does he usually drive?', type: 'adverb' },
      { word: 'Sometimes', translation: 'A veces', example: 'Do they sometimes call?', type: 'adverb' },
    ],
    grammar: {
      title: 'Preguntas en Presente Simple',
      explanation: 'Usamos Do/Does al inicio para hacer preguntas en presente simple.',
      examples: ['Do you work here?', 'Does she like pizza?', 'Do they speak English?'],
      rules: ['Do + I/you/we/they + verbo base?', 'Does + he/she/it + verbo base?', 'Respuestas cortas: Yes, I do / No, she doesn\'t'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: '___ she speak French?', options: ['Do', 'Does', 'Is', 'Are'], correctAnswer: 'Does', explanation: 'Con she usamos Does.' },
      { id: 'ex2', type: 'fill-blank', question: '___ you like chocolate?', correctAnswer: 'Do', explanation: 'Con you usamos Do.' },
    ],
    shadowingText: 'Do you like music? Does she work on Saturdays? Do they speak English? Does he live in Madrid? Yes, I do. No, she doesn\'t.',
  },
  {
    id: 'a1-16',
    level: 'A1',
    order: 16,
    title: 'Preposiciones de Lugar (In/On/At)',
    objective: 'Describir la ubicación de objetos',
    vocabulary: [
      { word: 'In', translation: 'En (dentro)', example: 'The book is in the bag.', type: 'phrase' },
      { word: 'On', translation: 'En (sobre)', example: 'The cup is on the table.', type: 'phrase' },
      { word: 'At', translation: 'En (punto)', example: 'I am at home.', type: 'phrase' },
      { word: 'Under', translation: 'Debajo', example: 'The cat is under the chair.', type: 'phrase' },
      { word: 'Behind', translation: 'Detrás', example: 'The car is behind the house.', type: 'phrase' },
    ],
    grammar: {
      title: 'Preposiciones de Lugar',
      explanation: 'In para espacios cerrados, on para superficies, at para puntos específicos.',
      examples: ['The book is in the box.', 'The keys are on the table.', 'I am at the station.'],
      rules: ['In = dentro de espacios', 'On = sobre superficies', 'At = puntos/lugares específicos'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'The picture is ___ the wall.', options: ['in', 'on', 'at', 'under'], correctAnswer: 'on', explanation: 'Usamos on para superficies verticales como paredes.' },
      { id: 'ex2', type: 'fill-blank', question: 'The cat is ___ the box.', correctAnswer: 'in', explanation: 'In para dentro de espacios cerrados.' },
    ],
    shadowingText: 'The book is on the table. The pen is in my bag. I am at school. The dog is under the chair. The car is behind the house.',
  },
  {
    id: 'a1-17',
    level: 'A1',
    order: 17,
    title: 'There is / There are',
    objective: 'Describir lo que hay en un lugar',
    vocabulary: [
      { word: 'There is', translation: 'Hay (singular)', example: 'There is a book on the table.', type: 'phrase' },
      { word: 'There are', translation: 'Hay (plural)', example: 'There are two cats.', type: 'phrase' },
      { word: 'Room', translation: 'Habitación', example: 'There are three rooms.', type: 'noun' },
      { word: 'Window', translation: 'Ventana', example: 'There is a big window.', type: 'noun' },
      { word: 'Door', translation: 'Puerta', example: 'There are two doors.', type: 'noun' },
    ],
    grammar: {
      title: 'There is / There are',
      explanation: 'There is para singular, there are para plural. Se usa para decir qué existe en un lugar.',
      examples: ['There is a cat.', 'There are five students.', 'There is a park near my house.'],
      rules: ['There is + sustantivo singular', 'There are + sustantivo plural', 'Negativo: There isn\'t / There aren\'t'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: '___ three books on the shelf.', options: ['There is', 'There are', 'It is', 'They are'], correctAnswer: 'There are', explanation: 'Three books es plural, usamos there are.' },
      { id: 'ex2', type: 'fill-blank', question: '___ a beautiful park in the city.', correctAnswer: 'There is', explanation: 'A park es singular, usamos there is.' },
    ],
    shadowingText: 'There is a big house on the hill. There are three bedrooms. There is one bathroom. There are two windows in each room.',
  },
  {
    id: 'a1-18',
    level: 'A1',
    order: 18,
    title: 'Preposiciones de Tiempo (In/On/At)',
    objective: 'Expresar cuándo ocurren las cosas',
    vocabulary: [
      { word: 'Monday', translation: 'Lunes', example: 'I work on Monday.', type: 'noun' },
      { word: 'January', translation: 'Enero', example: 'My birthday is in January.', type: 'noun' },
      { word: 'Week', translation: 'Semana', example: 'I study every week.', type: 'noun' },
      { word: 'Month', translation: 'Mes', example: 'We travel every month.', type: 'noun' },
      { word: 'Year', translation: 'Año', example: 'I was born in 1990.', type: 'noun' },
    ],
    grammar: {
      title: 'Preposiciones de Tiempo',
      explanation: 'In para meses/años/estaciones, on para días, at para horas.',
      examples: ['In January', 'On Monday', 'At 8 o\'clock', 'In the morning', 'On the weekend'],
      rules: ['In + mes/año/estación/parte del día', 'On + día de la semana/fecha', 'At + hora/noche/fin de semana'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'My birthday is ___ May.', options: ['in', 'on', 'at', 'the'], correctAnswer: 'in', explanation: 'Usamos in con meses.' },
      { id: 'ex2', type: 'fill-blank', question: 'The class starts ___ 9 AM.', correctAnswer: 'at', explanation: 'At para horas específicas.' },
    ],
    shadowingText: 'I wake up at seven in the morning. I work on Monday and Tuesday. My vacation is in July. The meeting is on Friday at three o\'clock.',
  },
  {
    id: 'a1-19',
    level: 'A1',
    order: 19,
    title: 'Wh- Questions (Información específica)',
    objective: 'Hacer preguntas para obtener información detallada',
    vocabulary: [
      { word: 'Who', translation: 'Quién', example: 'Who is that man?', type: 'phrase' },
      { word: 'Which', translation: 'Cuál', example: 'Which color do you prefer?', type: 'phrase' },
      { word: 'Whose', translation: 'De quién', example: 'Whose book is this?', type: 'phrase' },
      { word: 'How many', translation: 'Cuántos', example: 'How many people are there?', type: 'phrase' },
      { word: 'How old', translation: 'Qué edad', example: 'How old are you?', type: 'phrase' },
    ],
    grammar: {
      title: 'Wh- Questions',
      explanation: 'Las Wh- questions piden información específica (no Yes/No).',
      examples: ['Where do you live?', 'When is your birthday?', 'Why are you sad?', 'How do you go to work?'],
      rules: ['Wh- word + do/does + sujeto + verbo?', 'Wh- word + is/are + sujeto?', 'Who/What pueden ser el sujeto'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: '___ is your name?', options: ['What', 'Who', 'Which', 'Whose'], correctAnswer: 'What', explanation: 'What para preguntar por nombres y cosas.' },
      { id: 'ex2', type: 'fill-blank', question: '___ do you live?', correctAnswer: 'Where', explanation: 'Where para preguntar por lugares.' },
    ],
    shadowingText: 'What is your name? Where do you live? When is your birthday? Why do you study English? How do you travel to work?',
  },
  {
    id: 'a1-20',
    level: 'A1',
    order: 20,
    title: 'Adverbios de Frecuencia',
    objective: 'Expresar con qué frecuencia haces algo',
    vocabulary: [
      { word: 'Always', translation: 'Siempre', example: 'I always wake up early.', type: 'adverb' },
      { word: 'Usually', translation: 'Usualmente', example: 'She usually drinks coffee.', type: 'adverb' },
      { word: 'Sometimes', translation: 'A veces', example: 'I sometimes watch TV.', type: 'adverb' },
      { word: 'Rarely', translation: 'Raramente', example: 'He rarely eats meat.', type: 'adverb' },
      { word: 'Never', translation: 'Nunca', example: 'I never smoke.', type: 'adverb' },
    ],
    grammar: {
      title: 'Adverbios de Frecuencia',
      explanation: 'Los adverbios de frecuencia indican con qué regularidad ocurre algo. Van antes del verbo principal.',
      examples: ['I always study.', 'She usually works late.', 'They sometimes travel.', 'I never smoke.'],
      rules: ['Antes del verbo principal', 'Después del verbo to be', 'Orden: always > usually > often > sometimes > rarely > never'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'I ___ go to the gym. (100%)', options: ['never', 'sometimes', 'always', 'rarely'], correctAnswer: 'always', explanation: 'Always es 100% de frecuencia.' },
      { id: 'ex2', type: 'fill-blank', question: 'She ___ drinks coffee. (90%)', correctAnswer: 'usually', explanation: 'Usually indica alta frecuencia.' },
    ],
    shadowingText: 'I always wake up at seven. I usually have breakfast. I sometimes go to the gym. I rarely eat fast food. I never smoke.',
  },
  {
    id: 'a1-21',
    level: 'A1',
    order: 21,
    title: 'Imperativo (Instrucciones)',
    objective: 'Dar instrucciones y órdenes',
    vocabulary: [
      { word: 'Open', translation: 'Abrir', example: 'Open the door.', type: 'verb' },
      { word: 'Close', translation: 'Cerrar', example: 'Close the window.', type: 'verb' },
      { word: 'Listen', translation: 'Escuchar', example: 'Listen to me!', type: 'verb' },
      { word: 'Read', translation: 'Leer', example: 'Read this book.', type: 'verb' },
      { word: 'Write', translation: 'Escribir', example: 'Write your name.', type: 'verb' },
    ],
    grammar: {
      title: 'Imperativo',
      explanation: 'Usamos el imperativo para dar órdenes, instrucciones o consejos. Se forma con el verbo base.',
      examples: ['Open the door.', 'Don\'t close the window.', 'Be quiet!', 'Let\'s go!'],
      rules: ['Afirmativo: Verbo base', 'Negativo: Don\'t + verbo base', 'Para suavizar: Please + imperativo'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: '___ the book, please.', options: ['Opens', 'Opening', 'Open', 'To open'], correctAnswer: 'Open', explanation: 'Imperativo usa verbo base.' },
      { id: 'ex2', type: 'fill-blank', question: '___ be late!', correctAnswer: 'Don\'t', explanation: 'Don\'t para imperativo negativo.' },
    ],
    shadowingText: 'Open your book to page ten. Listen to the audio. Read the text. Write the answers. Don\'t talk during the test. Please be quiet.',
  },
  {
    id: 'a1-22',
    level: 'A1',
    order: 22,
    title: 'Can / Can\'t (Habilidad)',
    objective: 'Expresar habilidades y capacidades',
    vocabulary: [
      { word: 'Can', translation: 'Poder', example: 'I can swim.', type: 'verb' },
      { word: 'Can\'t', translation: 'No poder', example: 'I can\'t fly.', type: 'verb' },
      { word: 'Swim', translation: 'Nadar', example: 'She can swim well.', type: 'verb' },
      { word: 'Drive', translation: 'Conducir', example: 'He can drive a car.', type: 'verb' },
      { word: 'Speak', translation: 'Hablar', example: 'I can speak English.', type: 'verb' },
    ],
    grammar: {
      title: 'Can / Can\'t para Habilidad',
      explanation: 'Can expresa habilidad o capacidad. Es igual para todas las personas.',
      examples: ['I can play guitar.', 'She can\'t dance.', 'Can you swim?', 'Yes, I can. / No, I can\'t.'],
      rules: ['Can + verbo base', 'Can\'t + verbo base', 'Can + sujeto + verbo? para preguntas'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'She ___ speak three languages.', options: ['can', 'cans', 'is can', 'can to'], correctAnswer: 'can', explanation: 'Can es igual para todas las personas.' },
      { id: 'ex2', type: 'fill-blank', question: 'I ___ play the piano.', correctAnswer: 'can\'t', explanation: 'Can\'t para expresar inhabilidad.' },
    ],
    shadowingText: 'I can speak English and Spanish. I can swim but I can\'t dive. Can you play guitar? Yes, I can. Can she drive? No, she can\'t.',
  },
  {
    id: 'a1-23',
    level: 'A1',
    order: 23,
    title: 'Want to / Need to',
    objective: 'Expresar deseos e intenciones',
    vocabulary: [
      { word: 'Want', translation: 'Querer', example: 'I want to travel.', type: 'verb' },
      { word: 'Need', translation: 'Necesitar', example: 'I need to study.', type: 'verb' },
      { word: 'Travel', translation: 'Viajar', example: 'I want to travel to Paris.', type: 'verb' },
      { word: 'Learn', translation: 'Aprender', example: 'I want to learn French.', type: 'verb' },
      { word: 'Buy', translation: 'Comprar', example: 'I need to buy food.', type: 'verb' },
    ],
    grammar: {
      title: 'Want to / Need to + Infinitivo',
      explanation: 'Want to expresa deseos, need to expresa necesidad. Ambos van seguidos de infinitivo.',
      examples: ['I want to go home.', 'She needs to work.', 'Do you want to eat?', 'He doesn\'t need to come.'],
      rules: ['Want/need + to + verbo base', 'Tercera persona: wants to / needs to', 'Preguntas: Do you want to...?'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'I ___ learn English.', options: ['want', 'want to', 'wanting', 'wants'], correctAnswer: 'want to', explanation: 'Want to + infinitivo.' },
      { id: 'ex2', type: 'fill-blank', question: 'She ___ to study more.', correctAnswer: 'needs', explanation: 'Needs con tercera persona.' },
    ],
    shadowingText: 'I want to learn English. I need to practice every day. She wants to travel to Japan. He needs to buy a new car. Do you want to come with us?',
  },
  {
    id: 'a1-24',
    level: 'A1',
    order: 24,
    title: 'Like / Love / Hate + -ing',
    objective: 'Hablar de gustos y aversiones',
    vocabulary: [
      { word: 'Love', translation: 'Amar', example: 'I love reading.', type: 'verb' },
      { word: 'Like', translation: 'Gustar', example: 'She likes dancing.', type: 'verb' },
      { word: 'Hate', translation: 'Odiar', example: 'I hate waiting.', type: 'verb' },
      { word: 'Enjoy', translation: 'Disfrutar', example: 'He enjoys cooking.', type: 'verb' },
      { word: 'Prefer', translation: 'Preferir', example: 'I prefer walking.', type: 'verb' },
    ],
    grammar: {
      title: 'Like / Love / Hate + Gerundio',
      explanation: 'Estos verbos de preferencia van seguidos de gerundio (-ing) para expresar actividades.',
      examples: ['I like swimming.', 'She loves reading.', 'They hate studying.', 'I enjoy playing tennis.'],
      rules: ['Like/love/hate + verb-ing', 'Tercera persona: likes/loves/hates', 'También aceptan sustantivos: I like pizza'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'I love ___ books.', options: ['read', 'reading', 'to read', 'reads'], correctAnswer: 'reading', explanation: 'Love + gerundio (-ing).' },
      { id: 'ex2', type: 'fill-blank', question: 'She hates ___ up early. (wake)', correctAnswer: 'waking', explanation: 'Hate + gerundio.' },
    ],
    shadowingText: 'I love playing soccer. I like listening to music. I hate waking up early. She enjoys cooking. He prefers watching movies at home.',
  },
  {
    id: 'a1-25',
    level: 'A1',
    order: 25,
    title: 'La Hora',
    objective: 'Preguntar y decir la hora',
    vocabulary: [
      { word: 'O\'clock', translation: 'En punto', example: 'It\'s three o\'clock.', type: 'phrase' },
      { word: 'Half past', translation: 'Y media', example: 'It\'s half past five.', type: 'phrase' },
      { word: 'Quarter', translation: 'Cuarto', example: 'It\'s quarter past two.', type: 'noun' },
      { word: 'To', translation: 'Para', example: 'It\'s ten to six.', type: 'phrase' },
      { word: 'Past', translation: 'Pasado', example: 'It\'s twenty past four.', type: 'phrase' },
    ],
    grammar: {
      title: 'Telling Time',
      explanation: 'Para decir la hora usamos It\'s + hora. Past para después, to para antes de la hora.',
      examples: ['It\'s five o\'clock.', 'It\'s half past three.', 'It\'s quarter to six.', 'It\'s ten past nine.'],
      rules: ['O\'clock para horas exactas', 'Past para minutos después', 'To para minutos antes', 'Half past para :30'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'It\'s 3:30. It\'s ___.', options: ['three o\'clock', 'half past three', 'quarter past three', 'three thirty'], correctAnswer: 'half past three', explanation: ':30 es half past.' },
      { id: 'ex2', type: 'fill-blank', question: 'It\'s 5:15. It\'s ___ past five.', correctAnswer: 'quarter', explanation: ':15 es quarter past.' },
    ],
    shadowingText: 'What time is it? It\'s eight o\'clock. It\'s half past nine. It\'s quarter to seven. It\'s twenty past three. It\'s five to twelve.',
  },
  {
    id: 'a1-26',
    level: 'A1',
    order: 26,
    title: 'How much / How many',
    objective: 'Preguntar por cantidad y precios',
    vocabulary: [
      { word: 'How much', translation: 'Cuánto (incontable)', example: 'How much water?', type: 'phrase' },
      { word: 'How many', translation: 'Cuántos (contable)', example: 'How many apples?', type: 'phrase' },
      { word: 'Sugar', translation: 'Azúcar', example: 'I need some sugar.', type: 'noun' },
      { word: 'Apple', translation: 'Manzana', example: 'I want two apples.', type: 'noun' },
      { word: 'Bottle', translation: 'Botella', example: 'One bottle of water.', type: 'noun' },
    ],
    grammar: {
      title: 'How much / How many',
      explanation: 'How many para contables (pueden ir en plural), how much para incontables y precios.',
      examples: ['How many books?', 'How much water?', 'How much is it?', 'How many students are there?'],
      rules: ['How many + sustantivo plural', 'How much + sustantivo singular', 'How much para precios'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: '___ books do you have?', options: ['How much', 'How many', 'How', 'What'], correctAnswer: 'How many', explanation: 'Books es contable plural.' },
      { id: 'ex2', type: 'fill-blank', question: '___ is this shirt?', correctAnswer: 'How much', explanation: 'How much para precios.' },
    ],
    shadowingText: 'How many students are in the class? How much water do you drink? How much is this book? How many apples do you want?',
  },
  {
    id: 'a1-27',
    level: 'A1',
    order: 27,
    title: 'Contables e Incontables',
    objective: 'Diferenciar entre sustantivos contables e incontables',
    vocabulary: [
      { word: 'Water', translation: 'Agua', example: 'I drink water.', type: 'noun' },
      { word: 'Milk', translation: 'Leche', example: 'I need milk.', type: 'noun' },
      { word: 'Bread', translation: 'Pan', example: 'I buy bread.', type: 'noun' },
      { word: 'Rice', translation: 'Arroz', example: 'I eat rice.', type: 'noun' },
      { word: 'Cheese', translation: 'Queso', example: 'I love cheese.', type: 'noun' },
    ],
    grammar: {
      title: 'Sustantivos Contables e Incontables',
      explanation: 'Contables tienen plural (apple/apples), incontables no (water). Usan cuantificadores diferentes.',
      examples: ['Three apples', 'Some water', 'Many books', 'Much milk', 'A lot of sugar'],
      rules: ['Contables: a/an, many, few', 'Incontables: much, little, some', 'Some/any/a lot of para ambos'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'I drink ___ water.', options: ['many', 'much', 'a', 'three'], correctAnswer: 'much', explanation: 'Water es incontable, usamos much.' },
      { id: 'ex2', type: 'fill-blank', question: 'She buys ___ apples. (countable)', correctAnswer: 'many', explanation: 'Many para contables plurales.' },
    ],
    shadowingText: 'I drink a lot of water. I eat some bread. I buy many apples. I need much milk. There is a little sugar.',
  },
  {
    id: 'a1-28',
    level: 'A1',
    order: 28,
    title: 'Presente Continuo',
    objective: 'Describir lo que está pasando ahora',
    vocabulary: [
      { word: 'Now', translation: 'Ahora', example: 'I am studying now.', type: 'adverb' },
      { word: 'Right now', translation: 'Justo ahora', example: 'She is cooking right now.', type: 'phrase' },
      { word: 'At the moment', translation: 'En este momento', example: 'They are playing at the moment.', type: 'phrase' },
      { word: 'Running', translation: 'Corriendo', example: 'He is running.', type: 'verb' },
      { word: 'Watching', translation: 'Viendo', example: 'I am watching TV.', type: 'verb' },
    ],
    grammar: {
      title: 'Presente Continuo',
      explanation: 'Usamos el presente continuo para acciones que están ocurriendo ahora. Se forma con be + verb-ing.',
      examples: ['I am studying.', 'She is eating.', 'They are playing.', 'We are watching TV.'],
      rules: ['Be (am/is/are) + verb-ing', 'Para acciones en progreso', 'Señales: now, right now, at the moment'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'She ___ TV right now.', options: ['watch', 'watches', 'is watching', 'watching'], correctAnswer: 'is watching', explanation: 'Presente continuo: is + watching.' },
      { id: 'ex2', type: 'fill-blank', question: 'I ___ English now. (study)', correctAnswer: 'am studying', explanation: 'Am + studying para I.' },
    ],
    shadowingText: 'I am studying English right now. She is cooking dinner. They are watching a movie. He is running in the park. We are learning at the moment.',
  },
  {
    id: 'a1-29',
    level: 'A1',
    order: 29,
    title: 'Artículos: A/An/The',
    objective: 'Usar artículos correctamente',
    vocabulary: [
      { word: 'The', translation: 'El/La/Los/Las', example: 'The book is on the table.', type: 'phrase' },
      { word: 'A', translation: 'Un/Una', example: 'I have a cat.', type: 'phrase' },
      { word: 'An', translation: 'Un/Una', example: 'She is an artist.', type: 'phrase' },
      { word: 'University', translation: 'Universidad', example: 'I study at a university.', type: 'noun' },
      { word: 'Hour', translation: 'Hora', example: 'I wait for an hour.', type: 'noun' },
    ],
    grammar: {
      title: 'Artículos: A, An, The',
      explanation: 'A/an para general o primera mención. The para específico o segunda mención.',
      examples: ['I see a dog. The dog is big.', 'She is an engineer.', 'The sun is hot.'],
      rules: ['A antes de consonante', 'An antes de vocal sonora', 'The para algo específico o único'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'I see ___ elephant.', options: ['a', 'an', 'the', 'some'], correctAnswer: 'an', explanation: 'An antes de vocal sonora.' },
      { id: 'ex2', type: 'fill-blank', question: '___ sun is very bright today.', correctAnswer: 'The', explanation: 'The para cosas únicas.' },
    ],
    shadowingText: 'I have a car. The car is red. She is an artist. The artist is famous. I see a dog. The dog is playing. I eat an apple every day.',
  },
  {
    id: 'a1-30',
    level: 'A1',
    order: 30,
    title: 'Repaso General del Nivel A1',
    objective: 'Consolidar todo el contenido del nivel A1',
    vocabulary: [
      { word: 'Review', translation: 'Repasar', example: 'Let\'s review the lesson.', type: 'verb' },
      { word: 'Practice', translation: 'Practicar', example: 'I practice every day.', type: 'verb' },
      { word: 'Remember', translation: 'Recordar', example: 'I remember the rules.', type: 'verb' },
      { word: 'Understand', translation: 'Entender', example: 'I understand English.', type: 'verb' },
      { word: 'Improve', translation: 'Mejorar', example: 'I want to improve.', type: 'verb' },
    ],
    grammar: {
      title: 'Repaso Completo A1',
      explanation: 'Hemos cubierto: pronombres, to be, presente simple, can, presente continuo, preposiciones, artículos y más.',
      examples: ['I am a student.', 'She works every day.', 'They are studying now.', 'I can speak English.'],
      rules: ['Repasa cada estructura', 'Practica con ejercicios mixtos', 'Prepárate para el nivel A2'],
    },
    exercises: [
      { id: 'ex1', type: 'multiple-choice', question: 'She ___ English every day.', options: ['study', 'studies', 'is studying', 'studied'], correctAnswer: 'studies', explanation: 'Presente simple con she.' },
      { id: 'ex2', type: 'fill-blank', question: 'I ___ watching TV right now.', correctAnswer: 'am', explanation: 'Presente continuo con I.' },
      { id: 'ex3', type: 'multiple-choice', question: '___ do you live?', options: ['What', 'Where', 'When', 'Who'], correctAnswer: 'Where', explanation: 'Where para lugares.' },
      { id: 'ex4', type: 'fill-blank', question: 'There ___ three books on the table.', correctAnswer: 'are', explanation: 'There are para plural.' },
      { id: 'ex5', type: 'multiple-choice', question: 'I ___ play guitar.', options: ['can', 'cans', 'am can', 'can to'], correctAnswer: 'can', explanation: 'Can + verbo base.' },
    ],
    shadowingText: 'Hello! My name is Anna. I am from Mexico. I live in Madrid now. I work at a school. I teach English. I love my job. I can speak Spanish and English. Every day, I wake up at seven. I eat breakfast and go to work. Right now, I am teaching a class. My students are learning English. They study hard. I am very happy here.',
  },
]
