export interface ClassTopic {
  classNumber: number
  grammarPattern: string
  topicFunction: string
}

export const A1_CURRICULUM: ClassTopic[] = [
  { classNumber: 1, grammarPattern: 'Pronombres personales (I, you, he, she, it...)', topicFunction: 'Saludos y Presentaciones' },
  { classNumber: 2, grammarPattern: 'Verbo "To Be" (Afirmativo)', topicFunction: 'Nombres y Edad' },
  { classNumber: 3, grammarPattern: 'Verbo "To Be" (Negativo)', topicFunction: 'Países y Nacionalidades' },
  { classNumber: 4, grammarPattern: 'Verbo "To Be" (Pregunta y Respuestas Cortas)', topicFunction: 'Describir el estado de ánimo (I am happy)' },
  { classNumber: 5, grammarPattern: 'Artículos indefinidos (A/An)', topicFunction: 'Profesiones y Lugares de Trabajo' },
  { classNumber: 6, grammarPattern: 'Plurales (Regulares)', topicFunction: 'Objetos de la clase y el hogar' },
  { classNumber: 7, grammarPattern: 'Pronombres y adjetivos posesivos (My, your, his, her...)', topicFunction: 'La Familia' },
  { classNumber: 8, grammarPattern: 'Números (0-100)', topicFunction: 'Precios, Teléfonos' },
  { classNumber: 9, grammarPattern: 'Adjetivos (Colores, Tamaño)', topicFunction: 'Describir personas y cosas' },
  { classNumber: 10, grammarPattern: 'This/That, These/Those (Demostrativos)', topicFunction: 'Indicar la ubicación de un objeto' },
  { classNumber: 11, grammarPattern: 'Have got / Has got (Tener)', topicFunction: 'Posesiones' },
  { classNumber: 12, grammarPattern: 'Presente Simple (Afirmativo - Verbos de alta frecuencia)', topicFunction: 'Rutina y actividades diarias' },
  { classNumber: 13, grammarPattern: 'Presente Simple (Tercera persona singular "s")', topicFunction: 'La rutina de otra persona' },
  { classNumber: 14, grammarPattern: 'Presente Simple (Negativo con don\'t / doesn\'t)', topicFunction: 'Qué no haces habitualmente' },
  { classNumber: 15, grammarPattern: 'Presente Simple (Preguntas con Do / Does)', topicFunction: 'Preguntar sobre hábitos' },
  { classNumber: 16, grammarPattern: 'Preposiciones de Lugar (In, on, at)', topicFunction: 'Describir la ubicación' },
  { classNumber: 17, grammarPattern: 'There is / There are', topicFunction: 'Describir una ciudad o habitación' },
  { classNumber: 18, grammarPattern: 'Preposiciones de Tiempo (In, on, at)', topicFunction: 'Días de la semana y meses' },
  { classNumber: 19, grammarPattern: 'Wh- Questions (Where, when, why...)', topicFunction: 'Pedir información específica' },
  { classNumber: 20, grammarPattern: 'Adverbios de Frecuencia (Always, sometimes...)', topicFunction: 'Con qué frecuencia haces algo' },
  { classNumber: 21, grammarPattern: 'Imperativo (Afirmativo y Negativo)', topicFunction: 'Dar instrucciones y órdenes' },
  { classNumber: 22, grammarPattern: 'Can / Can\'t (Habilidad)', topicFunction: 'Decir lo que puedes o no puedes hacer' },
  { classNumber: 23, grammarPattern: 'Verbos + "to" + Verbo (I want to go)', topicFunction: 'Expresar deseos e intenciones' },
  { classNumber: 24, grammarPattern: 'Like / Love / Hate + -ing', topicFunction: 'Hablar de gustos y aversiones' },
  { classNumber: 25, grammarPattern: 'La hora (Preguntar y decir)', topicFunction: 'Organizar una reunión' },
  { classNumber: 26, grammarPattern: 'How much / How many', topicFunction: 'Preguntar por cantidad y precios' },
  { classNumber: 27, grammarPattern: 'Contables e Incontables', topicFunction: 'Comida y bebidas' },
  { classNumber: 28, grammarPattern: 'Presente Continuo (Forma básica)', topicFunction: 'Lo que está pasando ahora mismo' },
  { classNumber: 29, grammarPattern: 'Artículos (Repaso y el artículo "the")', topicFunction: 'Referirse a algo específico' },
  { classNumber: 30, grammarPattern: 'Repaso General del Nivel A1', topicFunction: 'Tarea de producción oral y escrita' },
]

export const A2_CURRICULUM: ClassTopic[] = [
  { classNumber: 31, grammarPattern: 'Pasado Simple (Ser/Estar)', topicFunction: 'Narrar el día de ayer' },
  { classNumber: 32, grammarPattern: 'Pasado Simple (Verbos Regulares)', topicFunction: 'Viajes pasados' },
  { classNumber: 33, grammarPattern: 'Pasado Simple (Verbos Irregulares comunes - parte 1)', topicFunction: 'Contar una historia personal corta' },
  { classNumber: 34, grammarPattern: 'Pasado Simple (Verbos Irregulares comunes - parte 2)', topicFunction: 'Eventos históricos' },
  { classNumber: 35, grammarPattern: 'Pasado Simple (Preguntas y Negativas)', topicFunction: 'Entrevista sobre el pasado' },
  { classNumber: 36, grammarPattern: 'Pasado Continuo (Forma básica)', topicFunction: 'Describir acciones en progreso en el pasado' },
  { classNumber: 37, grammarPattern: 'Pasado Continuo (Interrupciones con while/when)', topicFunction: 'Contar anécdotas' },
  { classNumber: 38, grammarPattern: 'Pasado Simple vs Pasado Continuo', topicFunction: 'Narrativa completa de eventos' },
  { classNumber: 39, grammarPattern: 'Futuro con "Going to" (Planes)', topicFunction: 'Planes e intenciones firmes' },
  { classNumber: 40, grammarPattern: 'Futuro con "Going to" (Predicciones basadas en evidencia)', topicFunction: 'Predecir el futuro cercano' },
  { classNumber: 41, grammarPattern: 'Futuro con "Will" (Decisiones espontáneas)', topicFunction: 'Decisiones en el momento' },
  { classNumber: 42, grammarPattern: 'Futuro con "Will" (Predicciones)', topicFunction: 'Predicciones generales' },
  { classNumber: 43, grammarPattern: 'Will vs Going to', topicFunction: 'Diferencia entre planes y decisiones' },
  { classNumber: 44, grammarPattern: 'Comparativos (Regulares)', topicFunction: 'Comparar dos cosas' },
  { classNumber: 45, grammarPattern: 'Comparativos (Irregulares)', topicFunction: 'Better, worse, more, less' },
  { classNumber: 46, grammarPattern: 'Superlativos (Regulares)', topicFunction: 'El más/menos de un grupo' },
  { classNumber: 47, grammarPattern: 'Superlativos (Irregulares)', topicFunction: 'Best, worst' },
  { classNumber: 48, grammarPattern: 'Adverbios de Modo', topicFunction: 'Describir cómo se hace algo' },
  { classNumber: 49, grammarPattern: 'Should / Shouldn\'t (Consejo)', topicFunction: 'Dar consejos' },
  { classNumber: 50, grammarPattern: 'Must / Mustn\'t (Obligación/Prohibición)', topicFunction: 'Expresar obligación' },
  { classNumber: 51, grammarPattern: 'Have to / Don\'t have to', topicFunction: 'Necesidad y falta de necesidad' },
  { classNumber: 52, grammarPattern: 'Modal Verbs Review', topicFunction: 'Diferencias entre modales' },
  { classNumber: 53, grammarPattern: 'Presente Perfecto (Ever/Never)', topicFunction: 'Experiencias de vida' },
  { classNumber: 54, grammarPattern: 'Presente Perfecto (Already/Yet/Just)', topicFunction: 'Acciones recientes' },
  { classNumber: 55, grammarPattern: 'Presente Perfecto vs Pasado Simple', topicFunction: 'Diferencia temporal' },
  { classNumber: 56, grammarPattern: 'Cuantificadores (Some/Any)', topicFunction: 'Compras' },
  { classNumber: 57, grammarPattern: 'Cuantificadores (Much/Many)', topicFunction: 'Grandes cantidades' },
  { classNumber: 58, grammarPattern: 'Cuantificadores (Few/Little)', topicFunction: 'Pequeñas cantidades' },
  { classNumber: 59, grammarPattern: 'Cuantificadores (A lot of / Lots of)', topicFunction: 'Expresar abundancia' },
  { classNumber: 60, grammarPattern: 'Voz Pasiva (Presente Simple - básica)', topicFunction: 'Procesos sencillos' },
  { classNumber: 61, grammarPattern: 'Voz Pasiva (Pasado Simple)', topicFunction: 'Cómo se hizo algo' },
  { classNumber: 62, grammarPattern: 'Preguntas Indirectas (Can you tell me...?)', topicFunction: 'Ser más educado al preguntar' },
  { classNumber: 63, grammarPattern: 'Phrasal Verbs Comunes (parte 1)', topicFunction: 'Get up, turn on, turn off' },
  { classNumber: 64, grammarPattern: 'Phrasal Verbs Comunes (parte 2)', topicFunction: 'Look for, put on, take off' },
  { classNumber: 65, grammarPattern: 'Used to (Hábitos pasados)', topicFunction: 'Cómo eran las cosas antes' },
  { classNumber: 66, grammarPattern: 'Adjetivos con -ed y -ing', topicFunction: 'Emociones y sentimientos' },
  { classNumber: 67, grammarPattern: 'Conectores básicos (and, but, because, so)', topicFunction: 'Unir ideas simples' },
  { classNumber: 68, grammarPattern: 'Conectores de secuencia (first, then, finally)', topicFunction: 'Narrar procesos' },
  { classNumber: 69, grammarPattern: 'Expresiones de tiempo futuro', topicFunction: 'Next week, tomorrow, in the future' },
  { classNumber: 70, grammarPattern: 'Repaso General del Nivel A2', topicFunction: 'Consolidación A2' },
]

export const B1_CURRICULUM: ClassTopic[] = [
  { classNumber: 71, grammarPattern: 'Presente Perfecto Simple (For/Since)', topicFunction: 'Duración' },
  { classNumber: 72, grammarPattern: 'Presente Perfecto Simple (Already/Yet)', topicFunction: 'Logros recientes' },
  { classNumber: 73, grammarPattern: 'Presente Perfecto Simple (Ever/Never)', topicFunction: 'Experiencias' },
  { classNumber: 74, grammarPattern: 'Presente Perfecto vs Pasado Simple (Revisión profunda)', topicFunction: 'Precisión temporal' },
  { classNumber: 75, grammarPattern: 'Presente Perfecto Simple (Just/Recently)', topicFunction: 'Acciones muy recientes' },
  { classNumber: 76, grammarPattern: 'Pasado Perfecto Simple (Introducción)', topicFunction: 'Evento antes de otro evento' },
  { classNumber: 77, grammarPattern: 'Pasado Perfecto Simple (Narrativa)', topicFunction: 'Flashbacks en historias' },
  { classNumber: 78, grammarPattern: 'Pasado Perfecto vs Pasado Simple', topicFunction: 'Orden de eventos en el pasado' },
  { classNumber: 79, grammarPattern: 'Pasado Perfecto (Already/Just)', topicFunction: 'Completación antes de otro momento' },
  { classNumber: 80, grammarPattern: 'Pasado Perfecto (When/Before/After)', topicFunction: 'Conectar eventos pasados' },
  { classNumber: 81, grammarPattern: 'Primer Condicional (If + Present, Will)', topicFunction: 'Situaciones probables' },
  { classNumber: 82, grammarPattern: 'Primer Condicional (Unless)', topicFunction: 'Condiciones negativas' },
  { classNumber: 83, grammarPattern: 'Primer Condicional (Variaciones)', topicFunction: 'Diferentes combinaciones' },
  { classNumber: 84, grammarPattern: 'Primer Condicional (Práctica intensiva)', topicFunction: 'Consecuencias futuras' },
  { classNumber: 85, grammarPattern: 'Primer Condicional (Contextos reales)', topicFunction: 'Aplicaciones prácticas' },
  { classNumber: 86, grammarPattern: 'Segundo Condicional (If + Past, Would)', topicFunction: 'Situaciones hipotéticas' },
  { classNumber: 87, grammarPattern: 'Segundo Condicional (Were en todas las personas)', topicFunction: 'Situaciones irreales' },
  { classNumber: 88, grammarPattern: 'Segundo Condicional (Could/Might)', topicFunction: 'Posibilidades hipotéticas' },
  { classNumber: 89, grammarPattern: 'Segundo Condicional (Práctica intensiva)', topicFunction: 'Deseos e imaginación' },
  { classNumber: 90, grammarPattern: 'Primer vs Segundo Condicional', topicFunction: 'Diferencia real vs irreal' },
  { classNumber: 91, grammarPattern: 'Cláusulas de Relativo (Who)', topicFunction: 'Definir personas' },
  { classNumber: 92, grammarPattern: 'Cláusulas de Relativo (Which)', topicFunction: 'Definir cosas' },
  { classNumber: 93, grammarPattern: 'Cláusulas de Relativo (That)', topicFunction: 'Alternativa informal' },
  { classNumber: 94, grammarPattern: 'Cláusulas de Relativo (Where)', topicFunction: 'Definir lugares' },
  { classNumber: 95, grammarPattern: 'Cláusulas de Relativo (Whose)', topicFunction: 'Posesión' },
  { classNumber: 96, grammarPattern: 'Estilo Indirecto (Declaraciones)', topicFunction: 'Reportar lo dicho' },
  { classNumber: 97, grammarPattern: 'Estilo Indirecto (Cambios de tiempo)', topicFunction: 'Transformaciones temporales' },
  { classNumber: 98, grammarPattern: 'Estilo Indirecto (Preguntas)', topicFunction: 'Reportar preguntas' },
  { classNumber: 99, grammarPattern: 'Estilo Indirecto (Órdenes)', topicFunction: 'Reportar comandos' },
  { classNumber: 100, grammarPattern: 'Estilo Indirecto (Say vs Tell)', topicFunction: 'Diferencias de uso' },
  { classNumber: 101, grammarPattern: 'Voz Pasiva (Presente Simple)', topicFunction: 'Procesos generales' },
  { classNumber: 102, grammarPattern: 'Voz Pasiva (Pasado Simple)', topicFunction: 'Eventos históricos' },
  { classNumber: 103, grammarPattern: 'Voz Pasiva (Presente Perfecto)', topicFunction: 'Acciones completadas' },
  { classNumber: 104, grammarPattern: 'Voz Pasiva (Con by)', topicFunction: 'Mencionar el agente' },
  { classNumber: 105, grammarPattern: 'Voz Pasiva (Omitir el agente)', topicFunction: 'Enfoque en la acción' },
  { classNumber: 106, grammarPattern: 'Verbos Modales (Might/May/Could - Probabilidad)', topicFunction: 'Especulación' },
  { classNumber: 107, grammarPattern: 'Verbos Modales (Could have/Might have)', topicFunction: 'Posibilidad en el pasado' },
  { classNumber: 108, grammarPattern: 'Verbos Modales (Should have)', topicFunction: 'Arrepentimiento/Crítica' },
  { classNumber: 109, grammarPattern: 'Verbos Modales (Must have)', topicFunction: 'Deducción fuerte pasada' },
  { classNumber: 110, grammarPattern: 'Verbos Modales (Revisión completa)', topicFunction: 'Matices de significado' },
  { classNumber: 111, grammarPattern: 'Conectores de Contraste (Although/However)', topicFunction: 'Contrastar ideas' },
  { classNumber: 112, grammarPattern: 'Conectores de Causa (Because of/Due to)', topicFunction: 'Explicar causas' },
  { classNumber: 113, grammarPattern: 'Conectores de Resultado (Therefore/Consequently)', topicFunction: 'Expresar resultados' },
  { classNumber: 114, grammarPattern: 'Conectores de Adición (Moreover/Furthermore)', topicFunction: 'Añadir información' },
  { classNumber: 115, grammarPattern: 'Conectores Mixtos', topicFunction: 'Argumentar y justificar' },
  { classNumber: 116, grammarPattern: 'Verbos + Gerundio (Enjoy, avoid, mind)', topicFunction: 'Preferencias negativas' },
  { classNumber: 117, grammarPattern: 'Verbos + Infinitivo (Want, need, hope)', topicFunction: 'Deseos y planes' },
  { classNumber: 118, grammarPattern: 'Verbos + Ambos (Like, love, hate)', topicFunction: 'Gustos con matices' },
  { classNumber: 119, grammarPattern: 'Verbos con cambio de significado (Stop, remember, forget)', topicFunction: 'Diferencias sutiles' },
  { classNumber: 120, grammarPattern: 'Repaso General del Nivel B1', topicFunction: 'Consolidación B1' },
]
