export interface ClassTopic {
  classNumber: number
  grammarPattern: string
  topicFunction: string
}

export const A1_CURRICULUM: ClassTopic[] = [
  { classNumber: 1, grammarPattern: 'Pronombres personales (I, you, he, she, it...)', topicFunction: 'Saludos y Presentaciones' },
  { classNumber: 2, grammarPattern: 'Verbo "To Be" (Afirmativo)', topicFunction: 'Nombres y Edad' },
  { classNumber: 3, grammarPattern: 'Verbo "To Be" (Negativo)', topicFunction: 'Países y Nacionalidades' },
  { classNumber: 4, grammarPattern: 'Verbo "To Be" (Pregunta y Respuestas Cortas)', topicFunction: 'Describir el estado de ánimo (I am happy)' },
  { classNumber: 5, grammarPattern: 'Artículos indefinidos (A/An)', topicFunction: 'Profesiones y Lugares de Trabajo' },
  { classNumber: 6, grammarPattern: 'Plurales (Regulares)', topicFunction: 'Objetos de la clase y el hogar' },
  { classNumber: 7, grammarPattern: 'Pronombres y adjetivos posesivos (My, your, his, her...)', topicFunction: 'La Familia' },
  { classNumber: 8, grammarPattern: 'Números (0-100)', topicFunction: 'Precios, Teléfonos' },
  { classNumber: 9, grammarPattern: 'Adjetivos (Colores, Tamaño)', topicFunction: 'Describir personas y cosas' },
  { classNumber: 10, grammarPattern: 'This/That, These/Those (Demostrativos)', topicFunction: 'Indicar la ubicación de un objeto' },
  { classNumber: 11, grammarPattern: 'Have got / Has got (Tener)', topicFunction: 'Posesiones' },
  { classNumber: 12, grammarPattern: 'Presente Simple (Afirmativo - Verbos de alta frecuencia)', topicFunction: 'Rutina y actividades diarias' },
  { classNumber: 13, grammarPattern: 'Presente Simple (Tercera persona singular "s")', topicFunction: 'La rutina de otra persona' },
  { classNumber: 14, grammarPattern: 'Presente Simple (Negativo con don\'t / doesn\'t)', topicFunction: 'Qué no haces habitualmente' },
  { classNumber: 15, grammarPattern: 'Presente Simple (Preguntas con Do / Does)', topicFunction: 'Preguntar sobre hábitos' },
  { classNumber: 16, grammarPattern: 'Preposiciones de Lugar (In, on, at)', topicFunction: 'Describir la ubicación' },
  { classNumber: 17, grammarPattern: 'There is / There are', topicFunction: 'Describir una ciudad o habitación' },
  { classNumber: 18, grammarPattern: 'Preposiciones de Tiempo (In, on, at)', topicFunction: 'Días de la semana y meses' },
  { classNumber: 19, grammarPattern: 'Wh- Questions (Where, when, why...)', topicFunction: 'Pedir información específica' },
  { classNumber: 20, grammarPattern: 'Adverbios de Frecuencia (Always, sometimes...)', topicFunction: 'Con qué frecuencia haces algo' },
  { classNumber: 21, grammarPattern: 'Imperativo (Afirmativo y Negativo)', topicFunction: 'Dar instrucciones y órdenes' },
  { classNumber: 22, grammarPattern: 'Can / Can\'t (Habilidad)', topicFunction: 'Decir lo que puedes o no puedes hacer' },
  { classNumber: 23, grammarPattern: 'Verbos + "to" + Verbo (I want to go)', topicFunction: 'Expresar deseos e intenciones' },
  { classNumber: 24, grammarPattern: 'Like / Love / Hate + -ing', topicFunction: 'Hablar de gustos y aversiones' },
  { classNumber: 25, grammarPattern: 'La hora (Preguntar y decir)', topicFunction: 'Organizar una reunión' },
  { classNumber: 26, grammarPattern: 'How much / How many', topicFunction: 'Preguntar por cantidad y precios' },
  { classNumber: 27, grammarPattern: 'Contables e Incontables', topicFunction: 'Comida y bebidas' },
  { classNumber: 28, grammarPattern: 'Presente Continuo (Forma básica)', topicFunction: 'Lo que está pasando ahora mismo' },
  { classNumber: 29, grammarPattern: 'Artículos (Repaso y el artículo "the")', topicFunction: 'Referirse a algo específico' },
  { classNumber: 30, grammarPattern: 'Repaso General del Nivel A1', topicFunction: 'Tarea de producción oral y escrita' },
]

export const A2_CURRICULUM: ClassTopic[] = [
  { classNumber: 31, grammarPattern: 'Pasado Simple (Ser/Estar)', topicFunction: 'Narrar el día de ayer' },
  { classNumber: 32, grammarPattern: 'Pasado Simple (Verbos Regulares)', topicFunction: 'Viajes pasados' },
  { classNumber: 33, grammarPattern: 'Pasado Simple (Verbos Irregulares comunes - parte 1)', topicFunction: 'Contar una historia personal corta' },
  { classNumber: 34, grammarPattern: 'Pasado Simple (Verbos Irregulares comunes - parte 2)', topicFunction: 'Eventos históricos' },
  { classNumber: 35, grammarPattern: 'Pasado Simple (Preguntas y Negativas)', topicFunction: 'Entrevista sobre el pasado' },
  { classNumber: 36, grammarPattern: 'Pasado Continuo (Forma básica)', topicFunction: 'Describir acciones en progreso en el pasado' },
  { classNumber: 37, grammarPattern: 'Pasado Continuo (Interrupciones con while/when)', topicFunction: 'Contar anécdotas' },
  { classNumber: 38, grammarPattern: 'Pasado Simple vs Pasado Continuo', topicFunction: 'Narrativa completa de eventos' },
  { classNumber: 39, grammarPattern: 'Futuro con "Going to" (Planes)', topicFunction: 'Planes e intenciones firmes' },
  { classNumber: 40, grammarPattern: 'Futuro con "Going to" (Predicciones basadas en evidencia)', topicFunction: 'Predecir el futuro cercano' },
  { classNumber: 41, grammarPattern: 'Futuro con "Will" (Decisiones espontáneas)', topicFunction: 'Decisiones en el momento' },
  { classNumber: 42, grammarPattern: 'Futuro con "Will" (Predicciones)', topicFunction: 'Predicciones generales' },
  { classNumber: 43, grammarPattern: 'Will vs Going to', topicFunction: 'Diferencia entre planes y decisiones' },
  { classNumber: 44, grammarPattern: 'Comparativos (Regulares)', topicFunction: 'Comparar dos cosas' },
  { classNumber: 45, grammarPattern: 'Comparativos (Irregulares)', topicFunction: 'Better, worse, more, less' },
  { classNumber: 46, grammarPattern: 'Superlativos (Regulares)', topicFunction: 'El más/menos de un grupo' },
  { classNumber: 47, grammarPattern: 'Superlativos (Irregulares)', topicFunction: 'Best, worst' },
  { classNumber: 48, grammarPattern: 'Adverbios de Modo', topicFunction: 'Describir cómo se hace algo' },
  { classNumber: 49, grammarPattern: 'Should / Shouldn\'t (Consejo)', topicFunction: 'Dar consejos' },
  { classNumber: 50, grammarPattern: 'Must / Mustn\'t (Obligación/Prohibición)', topicFunction: 'Expresar obligación' },
  { classNumber: 51, grammarPattern: 'Have to / Don\'t have to', topicFunction: 'Necesidad y falta de necesidad' },
  { classNumber: 52, grammarPattern: 'Modal Verbs Review', topicFunction: 'Diferencias entre modales' },
  { classNumber: 53, grammarPattern: 'Presente Perfecto (Ever/Never)', topicFunction: 'Experiencias de vida' },
  { classNumber: 54, grammarPattern: 'Presente Perfecto (Already/Yet/Just)', topicFunction: 'Acciones recientes' },
  { classNumber: 55, grammarPattern: 'Presente Perfecto vs Pasado Simple', topicFunction: 'Diferencia temporal' },
  { classNumber: 56, grammarPattern: 'Cuantificadores (Some/Any)', topicFunction: 'Compras' },
  { classNumber: 57, grammarPattern: 'Cuantificadores (Much/Many)', topicFunction: 'Grandes cantidades' },
  { classNumber: 58, grammarPattern: 'Cuantificadores (Few/Little)', topicFunction: 'Pequeñas cantidades' },
  { classNumber: 59, grammarPattern: 'Cuantificadores (A lot of / Lots of)', topicFunction: 'Expresar abundancia' },
  { classNumber: 60, grammarPattern: 'Voz Pasiva (Presente Simple - básica)', topicFunction: 'Procesos sencillos' },
  { classNumber: 61, grammarPattern: 'Voz Pasiva (Pasado Simple)', topicFunction: 'Cómo se hizo algo' },
  { classNumber: 62, grammarPattern: 'Preguntas Indirectas (Can you tell me...?)', topicFunction: 'Ser más educado al preguntar' },
  { classNumber: 63, grammarPattern: 'Phrasal Verbs Comunes (parte 1)', topicFunction: 'Get up, turn on, turn off' },
  { classNumber: 64, grammarPattern: 'Phrasal Verbs Comunes (parte 2)', topicFunction: 'Look for, put on, take off' },
  { classNumber: 65, grammarPattern: 'Used to (Hábitos pasados)', topicFunction: 'Cómo eran las cosas antes' },
  { classNumber: 66, grammarPattern: 'Adjetivos con -ed y -ing', topicFunction: 'Emociones y sentimientos' },
  { classNumber: 67, grammarPattern: 'Conectores básicos (and, but, because, so)', topicFunction: 'Unir ideas simples' },
  { classNumber: 68, grammarPattern: 'Conectores de secuencia (first, then, finally)', topicFunction: 'Narrar procesos' },
  { classNumber: 69, grammarPattern: 'Expresiones de tiempo futuro', topicFunction: 'Next week, tomorrow, in the future' },
  { classNumber: 70, grammarPattern: 'Repaso General del Nivel A2', topicFunction: 'Consolidación A2' },
]

export const B1_CURRICULUM: ClassTopic[] = [
  { classNumber: 71, grammarPattern: 'Presente Perfecto Simple (For/Since)', topicFunction: 'Duración' },
  { classNumber: 72, grammarPattern: 'Presente Perfecto Simple (Already/Yet)', topicFunction: 'Logros recientes' },
  { classNumber: 73, grammarPattern: 'Presente Perfecto Simple (Ever/Never)', topicFunction: 'Experiencias' },
  { classNumber: 74, grammarPattern: 'Presente Perfecto vs Pasado Simple (Revisión profunda)', topicFunction: 'Precisión temporal' },
  { classNumber: 75, grammarPattern: 'Presente Perfecto Simple (Just/Recently)', topicFunction: 'Acciones muy recientes' },
  { classNumber: 76, grammarPattern: 'Pasado Perfecto Simple (Introducción)', topicFunction: 'Evento antes de otro evento' },
  { classNumber: 77, grammarPattern: 'Pasado Perfecto Simple (Narrativa)', topicFunction: 'Flashbacks en historias' },
  { classNumber: 78, grammarPattern: 'Pasado Perfecto vs Pasado Simple', topicFunction: 'Orden de eventos en el pasado' },
  { classNumber: 79, grammarPattern: 'Pasado Perfecto (Already/Just)', topicFunction: 'Completación antes de otro momento' },
  { classNumber: 80, grammarPattern: 'Pasado Perfecto (When/Before/After)', topicFunction: 'Conectar eventos pasados' },
  { classNumber: 81, grammarPattern: 'Primer Condicional (If + Present, Will)', topicFunction: 'Situaciones probables' },
  { classNumber: 82, grammarPattern: 'Primer Condicional (Unless)', topicFunction: 'Condiciones negativas' },
  { classNumber: 83, grammarPattern: 'Primer Condicional (Variaciones)', topicFunction: 'Diferentes combinaciones' },
  { classNumber: 84, grammarPattern: 'Primer Condicional (Práctica intensiva)', topicFunction: 'Consecuencias futuras' },
  { classNumber: 85, grammarPattern: 'Primer Condicional (Contextos reales)', topicFunction: 'Aplicaciones prácticas' },
  { classNumber: 86, grammarPattern: 'Segundo Condicional (If + Past, Would)', topicFunction: 'Situaciones hipotéticas' },
  { classNumber: 87, grammarPattern: 'Segundo Condicional (Were en todas las personas)', topicFunction: 'Situaciones irreales' },
  { classNumber: 88, grammarPattern: 'Segundo Condicional (Could/Might)', topicFunction: 'Posibilidades hipotéticas' },
  { classNumber: 89, grammarPattern: 'Segundo Condicional (Práctica intensiva)', topicFunction: 'Deseos e imaginación' },
  { classNumber: 90, grammarPattern: 'Primer vs Segundo Condicional', topicFunction: 'Diferencia real vs irreal' },
  { classNumber: 91, grammarPattern: 'Cláusulas de Relativo (Who)', topicFunction: 'Definir personas' },
  { classNumber: 92, grammarPattern: 'Cláusulas de Relativo (Which)', topicFunction: 'Definir cosas' },
  { classNumber: 93, grammarPattern: 'Cláusulas de Relativo (That)', topicFunction: 'Alternativa informal' },
  { classNumber: 94, grammarPattern: 'Cláusulas de Relativo (Where)', topicFunction: 'Definir lugares' },
  { classNumber: 95, grammarPattern: 'Cláusulas de Relativo (Whose)', topicFunction: 'Posesión' },
  { classNumber: 96, grammarPattern: 'Estilo Indirecto (Declaraciones)', topicFunction: 'Reportar lo dicho' },
  { classNumber: 97, grammarPattern: 'Estilo Indirecto (Cambios de tiempo)', topicFunction: 'Transformaciones temporales' },
  { classNumber: 98, grammarPattern: 'Estilo Indirecto (Preguntas)', topicFunction: 'Reportar preguntas' },
  { classNumber: 99, grammarPattern: 'Estilo Indirecto (Órdenes)', topicFunction: 'Reportar comandos' },
  { classNumber: 100, grammarPattern: 'Estilo Indirecto (Say vs Tell)', topicFunction: 'Diferencias de uso' },
  { classNumber: 101, grammarPattern: 'Voz Pasiva (Presente Simple)', topicFunction: 'Procesos generales' },
  { classNumber: 102, grammarPattern: 'Voz Pasiva (Pasado Simple)', topicFunction: 'Eventos históricos' },
  { classNumber: 103, grammarPattern: 'Voz Pasiva (Presente Perfecto)', topicFunction: 'Acciones completadas' },
  { classNumber: 104, grammarPattern: 'Voz Pasiva (Con by)', topicFunction: 'Mencionar el agente' },
  { classNumber: 105, grammarPattern: 'Voz Pasiva (Omitir el agente)', topicFunction: 'Enfoque en la acción' },
  { classNumber: 106, grammarPattern: 'Verbos Modales (Might/May/Could - Probabilidad)', topicFunction: 'Especulación' },
  { classNumber: 107, grammarPattern: 'Verbos Modales (Could have/Might have)', topicFunction: 'Posibilidad en el pasado' },
  { classNumber: 108, grammarPattern: 'Verbos Modales (Should have)', topicFunction: 'Arrepentimiento/Crítica' },
  { classNumber: 109, grammarPattern: 'Verbos Modales (Must have)', topicFunction: 'Deducción fuerte pasada' },
  { classNumber: 110, grammarPattern: 'Verbos Modales (Revisión completa)', topicFunction: 'Matices de significado' },
  { classNumber: 111, grammarPattern: 'Conectores de Contraste (Although/However)', topicFunction: 'Contrastar ideas' },
  { classNumber: 112, grammarPattern: 'Conectores de Causa (Because of/Due to)', topicFunction: 'Explicar causas' },
  { classNumber: 113, grammarPattern: 'Conectores de Resultado (Therefore/Consequently)', topicFunction: 'Expresar resultados' },
  { classNumber: 114, grammarPattern: 'Conectores de Adición (Moreover/Furthermore)', topicFunction: 'Añadir información' },
  { classNumber: 115, grammarPattern: 'Conectores Mixtos', topicFunction: 'Argumentar y justificar' },
  { classNumber: 116, grammarPattern: 'Verbos + Gerundio (Enjoy, avoid, mind)', topicFunction: 'Preferencias negativas' },
  { classNumber: 117, grammarPattern: 'Verbos + Infinitivo (Want, need, hope)', topicFunction: 'Deseos y planes' },
  { classNumber: 118, grammarPattern: 'Verbos + Ambos (Like, love, hate)', topicFunction: 'Gustos con matices' },
  { classNumber: 119, grammarPattern: 'Verbos con cambio de significado (Stop, remember, forget)', topicFunction: 'Diferencias sutiles' },
  { classNumber: 120, grammarPattern: 'Repaso General del Nivel B1', topicFunction: 'Consolidación B1' },
]

export const B2_CURRICULUM: ClassTopic[] = [
  { classNumber: 121, grammarPattern: 'Presente Perfecto Continuo (Introducción)', topicFunction: 'Enfatizar la duración de una acción' },
  { classNumber: 122, grammarPattern: 'Presente Perfecto Continuo (For/Since)', topicFunction: 'Duración hasta ahora' },
  { classNumber: 123, grammarPattern: 'Presente Perfecto Continuo vs Presente Perfecto Simple', topicFunction: 'Acción vs Resultado' },
  { classNumber: 124, grammarPattern: 'Presente Perfecto Continuo (Práctica intensiva)', topicFunction: 'Acciones continuas relevantes' },
  { classNumber: 125, grammarPattern: 'Presente Perfecto Continuo (Contextos avanzados)', topicFunction: 'Aplicaciones complejas' },
  { classNumber: 126, grammarPattern: 'Tercer Condicional (If + Past Perfect, Would have)', topicFunction: 'Situaciones hipotéticas en el pasado' },
  { classNumber: 127, grammarPattern: 'Tercer Condicional (Arrepentimiento)', topicFunction: 'Expresar lamento por el pasado' },
  { classNumber: 128, grammarPattern: 'Tercer Condicional (Might have/Could have)', topicFunction: 'Posibilidades no realizadas' },
  { classNumber: 129, grammarPattern: 'Tercer Condicional (Práctica intensiva)', topicFunction: 'Situaciones imposibles pasadas' },
  { classNumber: 130, grammarPattern: 'Condicionales Mixtos', topicFunction: 'Combinar tiempos' },
  { classNumber: 131, grammarPattern: 'Modales Perfectos (Must have)', topicFunction: 'Deducción fuerte sobre el pasado' },
  { classNumber: 132, grammarPattern: 'Modales Perfectos (Might/May/Could have)', topicFunction: 'Posibilidad en el pasado' },
  { classNumber: 133, grammarPattern: 'Modales Perfectos (Should have/Ought to have)', topicFunction: 'Crítica y arrepentimiento' },
  { classNumber: 134, grammarPattern: 'Modales Perfectos (Can\'t/Couldn\'t have)', topicFunction: 'Imposibilidad en el pasado' },
  { classNumber: 135, grammarPattern: 'Modales Perfectos (Práctica mixta)', topicFunction: 'Especulación sobre el pasado' },
  { classNumber: 136, grammarPattern: 'Estilo Indirecto (Preguntas - revisión)', topicFunction: 'Reportar preguntas complejas' },
  { classNumber: 137, grammarPattern: 'Estilo Indirecto (Órdenes - revisión)', topicFunction: 'Reportar comandos formales' },
  { classNumber: 138, grammarPattern: 'Estilo Indirecto (Verbos de reporte avanzados)', topicFunction: 'Suggest, recommend, insist' },
  { classNumber: 139, grammarPattern: 'Estilo Indirecto (Cambios de lugar y tiempo)', topicFunction: 'Here/there, now/then' },
  { classNumber: 140, grammarPattern: 'Estilo Indirecto (Práctica completa)', topicFunction: 'Reportar conversaciones completas' },
  { classNumber: 141, grammarPattern: 'Wish/If only (Presente)', topicFunction: 'Expresar deseos sobre el presente' },
  { classNumber: 142, grammarPattern: 'Wish/If only (Pasado)', topicFunction: 'Expresar arrepentimientos' },
  { classNumber: 143, grammarPattern: 'Wish/If only (Futuro con would)', topicFunction: 'Deseos sobre comportamiento' },
  { classNumber: 144, grammarPattern: 'Wish vs Hope', topicFunction: 'Diferencias de uso' },
  { classNumber: 145, grammarPattern: 'Wish/If only (Práctica mixta)', topicFunction: 'Expresar deseos complejos' },
  { classNumber: 146, grammarPattern: 'Futuro Continuo (Will be + -ing)', topicFunction: 'Acciones en progreso futuras' },
  { classNumber: 147, grammarPattern: 'Futuro Perfecto (Will have + participle)', topicFunction: 'Completación en punto futuro' },
  { classNumber: 148, grammarPattern: 'Futuro Continuo vs Futuro Perfecto', topicFunction: 'Diferencias de enfoque' },
  { classNumber: 149, grammarPattern: 'Future in the Past (Was going to)', topicFunction: 'Planes no realizados' },
  { classNumber: 150, grammarPattern: 'Tiempos de Futuro (Revisión completa)', topicFunction: 'Dominio de futuros' },
  { classNumber: 151, grammarPattern: 'Cláusulas de Relativo (Definidas)', topicFunction: 'Información esencial' },
  { classNumber: 152, grammarPattern: 'Cláusulas de Relativo (No definidas)', topicFunction: 'Información extra' },
  { classNumber: 153, grammarPattern: 'Cláusulas de Relativo (Omisión del pronombre)', topicFunction: 'Relativas reducidas' },
  { classNumber: 154, grammarPattern: 'Cláusulas de Relativo (Con preposición)', topicFunction: 'Formal vs informal' },
  { classNumber: 155, grammarPattern: 'Cláusulas de Relativo (Práctica avanzada)', topicFunction: 'Redacción formal' },
  { classNumber: 156, grammarPattern: 'Inversión (After negative adverbials)', topicFunction: 'Énfasis formal' },
  { classNumber: 157, grammarPattern: 'Inversión (Rarely, seldom, never)', topicFunction: 'Expresiones negativas' },
  { classNumber: 158, grammarPattern: 'Inversión (Only, not only)', topicFunction: 'Estructuras enfáticas' },
  { classNumber: 159, grammarPattern: 'Inversión (Should/Had/Were)', topicFunction: 'Condicionales formales' },
  { classNumber: 160, grammarPattern: 'Inversión (Práctica completa)', topicFunction: 'Escritura formal' },
  { classNumber: 161, grammarPattern: 'Conectores de Énfasis (In fact, Indeed)', topicFunction: 'Reforzar argumentos' },
  { classNumber: 162, grammarPattern: 'Conectores de Énfasis (Moreover, Furthermore)', topicFunction: 'Añadir información' },
  { classNumber: 163, grammarPattern: 'Conectores de Contraste Avanzados (Nevertheless, Nonetheless)', topicFunction: 'Contraste formal' },
  { classNumber: 164, grammarPattern: 'Conectores de Secuencia (Subsequently, Eventually)', topicFunction: 'Orden cronológico formal' },
  { classNumber: 165, grammarPattern: 'Conectores Avanzados (Práctica mixta)', topicFunction: 'Argumentación compleja' },
  { classNumber: 166, grammarPattern: 'Voz Pasiva (Con verbos modales)', topicFunction: 'Must be done, should be seen' },
  { classNumber: 167, grammarPattern: 'Voz Pasiva (Perfectos)', topicFunction: 'Has been done, had been made' },
  { classNumber: 168, grammarPattern: 'Voz Pasiva (Continua)', topicFunction: 'Is being done, was being made' },
  { classNumber: 169, grammarPattern: 'Voz Pasiva (Estructuras complejas)', topicFunction: 'Combinaciones avanzadas' },
  { classNumber: 170, grammarPattern: 'Voz Pasiva (Impersonal con "it")', topicFunction: 'It is said that, It is believed' },
  { classNumber: 171, grammarPattern: 'Participios (-ing)', topicFunction: 'Adjetivos descriptivos' },
  { classNumber: 172, grammarPattern: 'Participios (-ed)', topicFunction: 'Adjetivos de sentimiento' },
  { classNumber: 173, grammarPattern: 'Participios (Cláusulas participiales)', topicFunction: 'Reducir oraciones' },
  { classNumber: 174, grammarPattern: 'Participios (Having done)', topicFunction: 'Secuencia de acciones' },
  { classNumber: 175, grammarPattern: 'Participios (Práctica avanzada)', topicFunction: 'Escritura sofisticada' },
  { classNumber: 176, grammarPattern: 'Phrasal Verbs (Separables)', topicFunction: 'Turn off, pick up' },
  { classNumber: 177, grammarPattern: 'Phrasal Verbs (Inseparables)', topicFunction: 'Look after, run into' },
  { classNumber: 178, grammarPattern: 'Phrasal Verbs (Con tres palabras)', topicFunction: 'Look forward to, put up with' },
  { classNumber: 179, grammarPattern: 'Phrasal Verbs (Formales vs informales)', topicFunction: 'Registro apropiado' },
  { classNumber: 180, grammarPattern: 'Repaso General del Nivel B2', topicFunction: 'Consolidación B2' },
]

export const C1_CURRICULUM: ClassTopic[] = [
  { classNumber: 181, grammarPattern: 'Inversión (Uso avanzado y estilístico)', topicFunction: 'Escritura formal y académica' },
  { classNumber: 182, grammarPattern: 'Conectores y Marcadores de Discurso Avanzados', topicFunction: 'Coherencia y cohesión en textos largos' },
  { classNumber: 183, grammarPattern: 'Cleft Sentences (It was X that..., What I need is...)', topicFunction: 'Resaltar información clave' },
  { classNumber: 184, grammarPattern: 'Discurso Indirecto (Verbos: allege, claim, refute, concede)', topicFunction: 'Reportar noticias y debates' },
  { classNumber: 185, grammarPattern: 'Condicionales Mixtos', topicFunction: 'Conectar el pasado con el presente hipotético' },
  { classNumber: 186, grammarPattern: 'Would rather / Had better', topicFunction: 'Expresar preferencia y consejo fuerte' },
  { classNumber: 187, grammarPattern: 'Voz Pasiva Impersonal (It is believed that..., He is thought to be...)', topicFunction: 'Discurso periodístico y académico' },
  { classNumber: 188, grammarPattern: 'Gerundios e Infinitivos (Casos especiales y excepciones)', topicFunction: 'Precisión gramatical' },
  { classNumber: 189, grammarPattern: 'Participle Clauses (Having finished, Seeing the danger...)', topicFunction: 'Reducción de oraciones y fluidez' },
  { classNumber: 190, grammarPattern: 'Tiempos Progresivos (Uso estilístico y matices)', topicFunction: 'Matizar acciones temporales' },
  { classNumber: 191, grammarPattern: 'Nominalization', topicFunction: 'Transformar verbos/adjetivos en sustantivos formales' },
  { classNumber: 192, grammarPattern: 'Hedging Language (Lenguaje cauteloso)', topicFunction: 'Expresiones académicas precisas' },
  { classNumber: 193, grammarPattern: 'Intensificadores y Mitigadores', topicFunction: 'Matizar el grado de certeza' },
  { classNumber: 194, grammarPattern: 'Elipsis (Omisión de elementos redundantes)', topicFunction: 'Economía lingüística' },
  { classNumber: 195, grammarPattern: 'Substitution (Sustitución para evitar repetición)', topicFunction: 'Cohesión textual avanzada' },
  { classNumber: 196, grammarPattern: 'Discourse Markers de Alto Nivel', topicFunction: 'Estructurar argumentos complejos' },
  { classNumber: 197, grammarPattern: 'Metáforas y Lenguaje Figurativo', topicFunction: 'Expresión sofisticada' },
  { classNumber: 198, grammarPattern: 'Colocaciones Académicas', topicFunction: 'Combinaciones naturales de palabras' },
  { classNumber: 199, grammarPattern: 'Fixed Expressions y Binomials', topicFunction: 'Expresiones idiomáticas formales' },
  { classNumber: 200, grammarPattern: 'Registro Formal vs Informal', topicFunction: 'Adecuación al contexto' },
  { classNumber: 201, grammarPattern: 'Subjuntive Mood (It is essential that he be...)', topicFunction: 'Mandatos y recomendaciones formales' },
  { classNumber: 202, grammarPattern: 'Emphatic Structures (It is...that emphasizes)', topicFunction: 'Énfasis retórico' },
  { classNumber: 203, grammarPattern: 'Fronting (Objeto/Adverbio al inicio)', topicFunction: 'Variación estilística' },
  { classNumber: 204, grammarPattern: 'Complex Passive Structures', topicFunction: 'Pasivas con múltiples elementos' },
  { classNumber: 205, grammarPattern: 'Advanced Conditional Structures', topicFunction: 'Variaciones de condicionales' },
  { classNumber: 206, grammarPattern: 'Modal Verbs - Nuanced Meanings', topicFunction: 'Matices sutiles de modales' },
  { classNumber: 207, grammarPattern: 'Phrasal Verbs Idiomáticos', topicFunction: 'Expresiones verbales complejas' },
  { classNumber: 208, grammarPattern: 'Prepositional Phrases Avanzadas', topicFunction: 'Expresiones preposicionales formales' },
  { classNumber: 209, grammarPattern: 'Adverbial Clauses Complejas', topicFunction: 'Subordinación avanzada' },
  { classNumber: 210, grammarPattern: 'Comparative Structures Avanzadas', topicFunction: 'Comparaciones sofisticadas' },
  { classNumber: 211, grammarPattern: 'Concession Clauses (Though, Although, Even though)', topicFunction: 'Expresar contraste' },
  { classNumber: 212, grammarPattern: 'Purpose Clauses Avanzadas (So that, In order that)', topicFunction: 'Expresar propósito formalmente' },
  { classNumber: 213, grammarPattern: 'Result Clauses (Such...that, So...that)', topicFunction: 'Expresar resultado intenso' },
  { classNumber: 214, grammarPattern: 'Time Clauses Avanzadas', topicFunction: 'Relaciones temporales complejas' },
  { classNumber: 215, grammarPattern: 'Conditional Clauses sin "if"', topicFunction: 'Were I, Should you, Had they' },
  { classNumber: 216, grammarPattern: 'Relative Clauses Reducidas', topicFunction: 'Cláusulas relativas sin pronombre' },
  { classNumber: 217, grammarPattern: 'Non-finite Clauses', topicFunction: 'Cláusulas sin verbo conjugado' },
  { classNumber: 218, grammarPattern: 'Comment Clauses (As you know, I believe)', topicFunction: 'Insertar comentarios' },
  { classNumber: 219, grammarPattern: 'Tag Questions Avanzadas', topicFunction: 'Confirmaciones sofisticadas' },
  { classNumber: 220, grammarPattern: 'Negative Inversion Avanzada', topicFunction: 'Inversión con barely, scarcely, seldom' },
  { classNumber: 221, grammarPattern: 'Aspectual Verbs (Keep, continue, cease)', topicFunction: 'Matizar duración/cese' },
  { classNumber: 222, grammarPattern: 'Causative Structures (Have/Get something done)', topicFunction: 'Expresar causalidad' },
  { classNumber: 223, grammarPattern: 'Sensory Verbs (See/Hear/Watch + object + verb)', topicFunction: 'Percepción con complementos' },
  { classNumber: 224, grammarPattern: 'Abstract Nouns y Nominalization Avanzada', topicFunction: 'Sustantivos abstractos complejos' },
  { classNumber: 225, grammarPattern: 'Academic Vocabulary - Alta Frecuencia', topicFunction: 'Vocabulario académico esencial' },
  { classNumber: 226, grammarPattern: 'Synonyms y Near-Synonyms', topicFunction: 'Diferencias sutiles de significado' },
  { classNumber: 227, grammarPattern: 'Connotation vs Denotation', topicFunction: 'Significado literal vs emocional' },
  { classNumber: 228, grammarPattern: 'Word Formation Avanzada', topicFunction: 'Prefijos y sufijos complejos' },
  { classNumber: 229, grammarPattern: 'Idioms y Expresiones Culturales', topicFunction: 'Expresiones idiomáticas avanzadas' },
  { classNumber: 230, grammarPattern: 'Repaso y Síntesis General C1', topicFunction: 'Consolidación completa del nivel C1' },
]

export const C2_CURRICULUM: ClassTopic[] = [
  { classNumber: 231, grammarPattern: 'Construcciones perifrásticas complejas (Such is..., Little did I know...)', topicFunction: 'Variedad estilística' },
  { classNumber: 232, grammarPattern: 'Vocabulario de Baja Frecuencia', topicFunction: 'Términos especializados' },
  { classNumber: 233, grammarPattern: 'Modismos Sofisticados', topicFunction: 'Expresiones idiomáticas avanzadas' },
  { classNumber: 234, grammarPattern: 'Registro Literario', topicFunction: 'Lenguaje de textos literarios' },
  { classNumber: 235, grammarPattern: 'Arcaísmos y Formas Históricas', topicFunction: 'Inglés histórico y formal' },
  { classNumber: 236, grammarPattern: 'Cláusulas Adverbiales complejas (Tiempo)', topicFunction: 'Relaciones temporales sutiles' },
  { classNumber: 237, grammarPattern: 'Cláusulas Adverbiales complejas (Condición)', topicFunction: 'Condiciones complejas' },
  { classNumber: 238, grammarPattern: 'Cláusulas Adverbiales complejas (Manera)', topicFunction: 'Expresar modo de acción' },
  { classNumber: 239, grammarPattern: 'Cláusulas Adverbiales complejas (Concesión)', topicFunction: 'Contraste avanzado' },
  { classNumber: 240, grammarPattern: 'Conexión lógica y fluidez máxima', topicFunction: 'Cohesión perfecta' },
  { classNumber: 241, grammarPattern: 'Collocations - Dominio completo', topicFunction: 'Combinaciones naturales perfectas' },
  { classNumber: 242, grammarPattern: 'Fixed Expressions - Dominio cultural', topicFunction: 'Expresiones culturalmente arraigadas' },
  { classNumber: 243, grammarPattern: 'Binomials y Trinomials', topicFunction: 'Pares y tríos fijos' },
  { classNumber: 244, grammarPattern: 'Similes y Metáforas Extendidas', topicFunction: 'Lenguaje figurativo complejo' },
  { classNumber: 245, grammarPattern: 'Euphemisms y Euforia', topicFunction: 'Lenguaje diplomático' },
  { classNumber: 246, grammarPattern: 'Irony y Sarcasm', topicFunction: 'Tonos implícitos' },
  { classNumber: 247, grammarPattern: 'Understatement y Hyperbole', topicFunction: 'Minimización y exageración' },
  { classNumber: 248, grammarPattern: 'Uso flexible de tiempos verbales (Matices)', topicFunction: 'Expresar sutilezas temporales' },
  { classNumber: 249, grammarPattern: 'Aspectos verbales avanzados', topicFunction: 'Perfective, Imperfective, Habitual' },
  { classNumber: 250, grammarPattern: 'Modalidad compleja', topicFunction: 'Certeza, obligación, posibilidad sutiles' },
  { classNumber: 251, grammarPattern: 'Phrasal Verbs Trisílabos', topicFunction: 'Verbos frasales de tres elementos' },
  { classNumber: 252, grammarPattern: 'Phrasal Verbs Idiomáticos Avanzados', topicFunction: 'Expresiones idiomáticas con verbos' },
  { classNumber: 253, grammarPattern: 'Prepositional Phrases Idiomáticas', topicFunction: 'Frases preposicionales fijas' },
  { classNumber: 254, grammarPattern: 'Adverbial Phrases Complejas', topicFunction: 'Expresiones adverbiales sofisticadas' },
  { classNumber: 255, grammarPattern: 'Sentence Adverbials Avanzados', topicFunction: 'Adverbios que modifican oraciones' },
  { classNumber: 256, grammarPattern: 'Dominio del Registro Académico', topicFunction: 'Lenguaje académico perfecto' },
  { classNumber: 257, grammarPattern: 'Dominio del Registro Profesional', topicFunction: 'Lenguaje corporativo impecable' },
  { classNumber: 258, grammarPattern: 'Dominio del Registro Literario', topicFunction: 'Estilo literario sofisticado' },
  { classNumber: 259, grammarPattern: 'Dominio del Registro Informal Culto', topicFunction: 'Informalidad educada' },
  { classNumber: 260, grammarPattern: 'Cambio de Registro Fluido', topicFunction: 'Transiciones entre registros' },
  { classNumber: 261, grammarPattern: 'Técnicas Retóricas Avanzadas', topicFunction: 'Persuasión y argumentación' },
  { classNumber: 262, grammarPattern: 'Análisis Crítico del Discurso', topicFunction: 'Deconstruir argumentos complejos' },
  { classNumber: 263, grammarPattern: 'Producción de Textos Complejos', topicFunction: 'Crear ensayos sofisticados' },
  { classNumber: 264, grammarPattern: 'Interpretación de Textos Literarios', topicFunction: 'Analizar literatura compleja' },
  { classNumber: 265, grammarPattern: 'Dominio de la Ambigüedad', topicFunction: 'Interpretar y crear ambigüedad' },
  { classNumber: 266, grammarPattern: 'Simulacro de Examen C2 - Parte 1', topicFunction: 'Práctica de examen formal' },
  { classNumber: 267, grammarPattern: 'Simulacro de Examen C2 - Parte 2', topicFunction: 'Evaluación comprensiva' },
  { classNumber: 268, grammarPattern: 'Simulacro de Examen C2 - Parte 3', topicFunction: 'Producción oral y escrita' },
  { classNumber: 269, grammarPattern: 'Refinamiento y Perfeccionamiento', topicFunction: 'Pulir habilidades al máximo' },
  { classNumber: 270, grammarPattern: 'Repaso y Síntesis General C2', topicFunction: 'Consolidación del dominio maestro' },
]
