import { Lesson, Level, PlacementTestQuestion, Achievement } from './types'
import { B1_LESSONS, B2_LESSONS, C1_LESSONS, C2_LESSONS } from './advanced-lessons'

export const LEVELS: Level[] = ['Beginner', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2']

export const LEVEL_INFO: Record<Level, { title: string; description: string; lessons: number }> = {
  Beginner: {
    title: 'Principiante',
    description: 'Comienza tu viaje con saludos básicos y frases cotidianas',
    lessons: 5,
  },
  A1: {
    title: 'A1 - Elemental',
    description: 'Construye tu base con oraciones simples y situaciones comunes',
    lessons: 30,
  },
  A2: {
    title: 'A2 - Pre-Intermedio',
    description: 'Exprésate en tareas rutinarias y temas familiares',
    lessons: 40,
  },
  B1: {
    title: 'B1 - Intermedio',
    description: 'Maneja la mayoría de situaciones de viaje y discute temas familiares',
    lessons: 50,
  },
  B2: {
    title: 'B2 - Intermedio Alto',
    description: 'Interactúa con fluidez y comprende textos complejos',
    lessons: 60,
  },
  C1: {
    title: 'C1 - Avanzado',
    description: 'Expresa ideas con fluidez y usa el lenguaje con flexibilidad',
    lessons: 50,
  },
  C2: {
    title: 'C2 - Dominio',
    description: 'Domina el idioma con precisión y sutileza',
    lessons: 40,
  },
}

export const LESSONS: Record<Level, Lesson[]> = {
  Beginner: [
    {
      id: 'beginner-1',
      level: 'Beginner',
      order: 1,
      title: 'Greetings and Introductions',
      objective: 'Aprende cómo saludar a las personas y presentarte',
      vocabulary: [
        { word: 'Hello', translation: 'Hola', example: 'Hello, my name is John.', type: 'phrase' },
        { word: 'Goodbye', translation: 'Adiós', example: 'Goodbye, see you later!', type: 'phrase' },
        { word: 'Thank you', translation: 'Gracias', example: 'Thank you for your help.', type: 'phrase' },
        { word: 'Please', translation: 'Por favor', example: 'Please sit down.', type: 'phrase' },
        { word: 'Name', translation: 'Nombre', example: 'My name is Maria.', type: 'noun' },
      ],
      grammar: {
        title: 'Pronombres Personales y "To Be"',
        explanation: 'Los pronombres personales (I, you, he, she, it, we, they) se usan con el verbo "to be" (am, is, are) para presentarte a ti mismo y a otros.',
        examples: ['I am a student.', 'You are nice.', 'She is my friend.', 'We are learning English.'],
        rules: [
          'Usa "am" con I',
          'Usa "is" con he, she, it',
          'Usa "are" con you, we, they',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'How do you greet someone in the morning?',
          options: ['Good night', 'Good morning', 'Goodbye', 'Thank you'],
          correctAnswer: 'Good morning',
          explanation: 'We use "Good morning" to greet people before noon.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'My name ___ John.',
          correctAnswer: 'is',
          explanation: 'We use "is" with singular subjects like "name".',
        },
        {
          id: 'ex3',
          type: 'multiple-choice',
          question: 'What is the correct response to "Thank you"?',
          options: ['Hello', 'You are welcome', 'Goodbye', 'Please'],
          correctAnswer: 'You are welcome',
          explanation: '"You are welcome" (or "You\'re welcome") is the polite response to "Thank you".',
        },
      ],
      shadowingText: 'Hello! My name is Alex. I am happy to meet you. How are you today?',
    },
    {
      id: 'beginner-2',
      level: 'Beginner',
      order: 2,
      title: 'Numbers and Counting',
      objective: 'Learn numbers from 1 to 100 and how to count',
      vocabulary: [
        { word: 'One', translation: 'Uno', example: 'I have one apple.', type: 'noun' },
        { word: 'Two', translation: 'Dos', example: 'There are two cats.', type: 'noun' },
        { word: 'Ten', translation: 'Diez', example: 'I can count to ten.', type: 'noun' },
        { word: 'Twenty', translation: 'Veinte', example: 'She is twenty years old.', type: 'noun' },
        { word: 'Hundred', translation: 'Cien', example: 'One hundred dollars.', type: 'noun' },
      ],
      grammar: {
        title: 'Numbers and Quantity',
        explanation: 'Numbers are used to count objects and express quantity. Learn cardinal numbers (one, two, three) for counting.',
        examples: ['I have three books.', 'There are five students.', 'She has twenty pencils.'],
        rules: [
          'Numbers 1-12 are unique words',
          'Numbers 13-19 end in -teen',
          'Multiples of 10 end in -ty',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'What comes after nineteen?',
          options: ['Eighteen', 'Twenty', 'Thirty', 'Twenty-one'],
          correctAnswer: 'Twenty',
          explanation: 'Twenty (20) comes after nineteen (19).',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'I have ___ hands.',
          correctAnswer: 'two',
          explanation: 'Humans have two hands.',
        },
      ],
      shadowingText: 'One, two, three, four, five. I can count from one to five. Six, seven, eight, nine, ten.',
    },
    {
      id: 'beginner-3',
      level: 'Beginner',
      order: 3,
      title: 'Colors and Objects',
      objective: 'Identify common colors and everyday objects',
      vocabulary: [
        { word: 'Red', translation: 'Rojo', example: 'The apple is red.', type: 'adjective' },
        { word: 'Blue', translation: 'Azul', example: 'The sky is blue.', type: 'adjective' },
        { word: 'Book', translation: 'Libro', example: 'I read a book.', type: 'noun' },
        { word: 'Table', translation: 'Mesa', example: 'The table is big.', type: 'noun' },
        { word: 'Chair', translation: 'Silla', example: 'Please sit on the chair.', type: 'noun' },
      ],
      grammar: {
        title: 'Articles and Adjectives',
        explanation: 'Articles (a, an, the) come before nouns. Adjectives describe nouns and usually come before them.',
        examples: ['A red car', 'An old book', 'The blue house', 'A beautiful day'],
        rules: [
          'Use "a" before consonant sounds',
          'Use "an" before vowel sounds',
          'Use "the" for specific things',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'Choose the correct article: ___ apple is red.',
          options: ['A', 'An', 'The', 'Some'],
          correctAnswer: 'The',
          explanation: 'We use "the" when talking about a specific apple.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'The sky is ___.',
          correctAnswer: 'blue',
          explanation: 'The sky is typically blue in color.',
        },
      ],
      shadowingText: 'This is a red book. That is a blue chair. The table is brown. I like green and yellow.',
    },
    {
      id: 'beginner-4',
      level: 'Beginner',
      order: 4,
      title: 'Family and Relationships',
      objective: 'Talk about family members and relationships',
      vocabulary: [
        { word: 'Mother', translation: 'Madre', example: 'My mother is kind.', type: 'noun' },
        { word: 'Father', translation: 'Padre', example: 'His father works hard.', type: 'noun' },
        { word: 'Sister', translation: 'Hermana', example: 'I have one sister.', type: 'noun' },
        { word: 'Brother', translation: 'Hermano', example: 'My brother is tall.', type: 'noun' },
        { word: 'Friend', translation: 'Amigo/a', example: 'She is my best friend.', type: 'noun' },
      ],
      grammar: {
        title: 'Possessive Adjectives',
        explanation: 'Possessive adjectives (my, your, his, her, its, our, their) show ownership.',
        examples: ['My mother', 'Your sister', 'His father', 'Her brother', 'Our family'],
        rules: [
          'My - belongs to me',
          'Your - belongs to you',
          'His/Her - belongs to him/her',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'Choose the correct possessive: This is ___ mother.',
          options: ['I', 'my', 'me', 'mine'],
          correctAnswer: 'my',
          explanation: 'We use "my" as a possessive adjective before a noun.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She loves ___ family.',
          correctAnswer: 'her',
          explanation: 'We use "her" to show something belongs to a female person.',
        },
      ],
      shadowingText: 'This is my family. My mother is Maria. My father is John. I have one sister and one brother.',
    },
    {
      id: 'beginner-5',
      level: 'Beginner',
      order: 5,
      title: 'Daily Activities',
      objective: 'Describe simple daily activities and routines',
      vocabulary: [
        { word: 'Eat', translation: 'Comer', example: 'I eat breakfast.', type: 'verb' },
        { word: 'Sleep', translation: 'Dormir', example: 'I sleep at night.', type: 'verb' },
        { word: 'Work', translation: 'Trabajar', example: 'She works every day.', type: 'verb' },
        { word: 'Study', translation: 'Estudiar', example: 'We study English.', type: 'verb' },
        { word: 'Play', translation: 'Jugar', example: 'They play soccer.', type: 'verb' },
      ],
      grammar: {
        title: 'Simple Present Tense',
        explanation: 'Use simple present to talk about habits, routines, and general facts.',
        examples: ['I eat breakfast every day.', 'She works at a hospital.', 'They study English.'],
        rules: [
          'Add -s for he, she, it',
          'I/you/we/they + base verb',
          'He/she/it + verb + s',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'She ___ every morning.',
          options: ['study', 'studies', 'studying', 'studied'],
          correctAnswer: 'studies',
          explanation: 'With "she", we add -ies to "study".',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'I ___ breakfast at 8 AM.',
          correctAnswer: 'eat',
          explanation: 'With "I", we use the base form of the verb.',
        },
      ],
      shadowingText: 'Every day, I wake up at 7 AM. I eat breakfast. Then I go to work. In the evening, I study English.',
    },
  ],
  A1: [
    {
      id: 'a1-1',
      level: 'A1',
      order: 1,
      title: 'Asking Questions',
      objective: 'Form and answer basic questions',
      vocabulary: [
        { word: 'What', translation: 'Qué', example: 'What is your name?', type: 'phrase' },
        { word: 'Where', translation: 'Dónde', example: 'Where do you live?', type: 'phrase' },
        { word: 'When', translation: 'Cuándo', example: 'When is your birthday?', type: 'phrase' },
        { word: 'Why', translation: 'Por qué', example: 'Why are you happy?', type: 'phrase' },
        { word: 'How', translation: 'Cómo', example: 'How are you?', type: 'phrase' },
      ],
      grammar: {
        title: 'Question Formation',
        explanation: 'Questions start with question words (what, where, when, why, how) or auxiliary verbs (do, does, is, are).',
        examples: ['What is your name?', 'Where do you live?', 'Are you happy?', 'Do you like pizza?'],
        rules: [
          'Question word + verb + subject',
          'Use "do/does" for present simple questions',
          'Invert subject and "be" for "be" questions',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: '___ is your name?',
          options: ['What', 'Where', 'When', 'Why'],
          correctAnswer: 'What',
          explanation: 'We use "What" to ask about things, including names.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: '___ do you live?',
          correctAnswer: 'Where',
          explanation: 'We use "Where" to ask about locations.',
        },
      ],
      shadowingText: 'What is your name? Where are you from? How old are you? When is your birthday?',
    },
    {
      id: 'a1-2',
      level: 'A1',
      order: 2,
      title: 'Shopping and Prices',
      objective: 'Learn vocabulary for shopping and discussing prices',
      vocabulary: [
        { word: 'Buy', translation: 'Comprar', example: 'I want to buy shoes.', type: 'verb' },
        { word: 'Price', translation: 'Precio', example: 'What is the price?', type: 'noun' },
        { word: 'Money', translation: 'Dinero', example: 'I need more money.', type: 'noun' },
        { word: 'Expensive', translation: 'Caro', example: 'This car is expensive.', type: 'adjective' },
        { word: 'Cheap', translation: 'Barato', example: 'These shoes are cheap.', type: 'adjective' },
      ],
      grammar: {
        title: 'Want and Need',
        explanation: 'Use "want" for desires and "need" for necessities, followed by "to" + verb or a noun.',
        examples: ['I want to buy a book.', 'She needs a new phone.', 'They want coffee.'],
        rules: [
          'Want/need + to + verb',
          'Want/need + noun',
          'How much is/are...? for prices',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I ___ to buy a new phone.',
          options: ['want', 'wants', 'wanting', 'wanted'],
          correctAnswer: 'want',
          explanation: 'With "I", we use "want" (base form).',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'How much ___ this shirt?',
          correctAnswer: 'is',
          explanation: 'We use "is" with singular items when asking about price.',
        },
      ],
      shadowingText: 'I want to buy a new shirt. How much is it? Is it expensive? No, it is cheap. I will buy it.',
    },
    {
      id: 'a1-3',
      level: 'A1',
      order: 3,
      title: 'Food and Meals',
      objective: 'Talk about food preferences and meals',
      vocabulary: [
        { word: 'Food', translation: 'Comida', example: 'I love Italian food.', type: 'noun' },
        { word: 'Drink', translation: 'Bebida', example: 'Water is a healthy drink.', type: 'noun' },
        { word: 'Delicious', translation: 'Delicioso', example: 'This pizza is delicious.', type: 'adjective' },
        { word: 'Hungry', translation: 'Hambriento', example: 'I am hungry.', type: 'adjective' },
        { word: 'Thirsty', translation: 'Sediento', example: 'She is thirsty.', type: 'adjective' },
      ],
      grammar: {
        title: 'Like, Love, Prefer',
        explanation: 'Use these verbs to express preferences about food and other things.',
        examples: ['I like apples.', 'She loves chocolate.', 'We prefer tea to coffee.'],
        rules: [
          'Like/love/prefer + noun',
          'Like/love/prefer + verb-ing',
          'Prefer A to B',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I ___ pizza very much.',
          options: ['like', 'likes', 'liking', 'liked'],
          correctAnswer: 'like',
          explanation: 'With "I", we use "like" without -s.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She ___ chocolate cake.',
          correctAnswer: 'loves',
          explanation: 'With "she", we add -s to "love".',
        },
      ],
      shadowingText: 'I like pizza and pasta. My favorite food is sushi. I love chocolate. Do you prefer tea or coffee?',
    },
    {
      id: 'a1-4',
      level: 'A1',
      order: 4,
      title: 'Time and Schedules',
      objective: 'Tell time and talk about schedules',
      vocabulary: [
        { word: 'Time', translation: 'Tiempo/Hora', example: 'What time is it?', type: 'noun' },
        { word: 'Clock', translation: 'Reloj', example: 'Look at the clock.', type: 'noun' },
        { word: 'Morning', translation: 'Mañana', example: 'I wake up in the morning.', type: 'noun' },
        { word: 'Afternoon', translation: 'Tarde', example: 'We meet in the afternoon.', type: 'noun' },
        { word: 'Night', translation: 'Noche', example: 'Good night!', type: 'noun' },
      ],
      grammar: {
        title: 'Telling Time',
        explanation: 'Use "It is" or "It\'s" followed by the time. Use "at" for specific times.',
        examples: ['It is 3 o\'clock.', 'It\'s half past two.', 'I wake up at 7 AM.'],
        rules: [
          'Use o\'clock for exact hours',
          'Use "past" for minutes after the hour',
          'Use "to" for minutes before the hour',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'What time is it? It\'s three ___.',
          options: ['o\'clock', 'clock', 'hours', 'time'],
          correctAnswer: 'o\'clock',
          explanation: 'We use "o\'clock" for exact hours.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'I go to bed ___ 10 PM.',
          correctAnswer: 'at',
          explanation: 'We use "at" for specific times.',
        },
      ],
      shadowingText: 'What time is it? It is eight o\'clock. I wake up at seven in the morning. I go to bed at ten at night.',
    },
    {
      id: 'a1-5',
      level: 'A1',
      order: 5,
      title: 'Weather and Seasons',
      objective: 'Describe weather conditions and seasons',
      vocabulary: [
        { word: 'Weather', translation: 'Clima', example: 'The weather is nice today.', type: 'noun' },
        { word: 'Sunny', translation: 'Soleado', example: 'It is sunny outside.', type: 'adjective' },
        { word: 'Rain', translation: 'Lluvia', example: 'I like the rain.', type: 'noun' },
        { word: 'Cold', translation: 'Frío', example: 'It is cold in winter.', type: 'adjective' },
        { word: 'Hot', translation: 'Caliente', example: 'Summer is hot.', type: 'adjective' },
      ],
      grammar: {
        title: 'Weather Expressions',
        explanation: 'Use "It is" or "It\'s" to describe weather. Weather is always singular.',
        examples: ['It is sunny.', 'It is raining.', 'It is cold today.', 'The weather is nice.'],
        rules: [
          'It is + adjective (sunny, cold, hot)',
          'It is + verb-ing (raining, snowing)',
          'The weather is + adjective',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: '___ is sunny today.',
          options: ['It', 'This', 'There', 'Weather'],
          correctAnswer: 'It',
          explanation: 'We use "It" to talk about weather.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'It is ___ outside. I need a jacket.',
          correctAnswer: 'cold',
          explanation: 'When we need a jacket, it means the weather is cold.',
        },
      ],
      shadowingText: 'How is the weather today? It is sunny and warm. I love spring. In winter, it is very cold and sometimes it snows.',
    },
    {
      id: 'a1-6',
      level: 'A1',
      order: 6,
      title: 'Places in the City',
      objective: 'Name and locate places in a city',
      vocabulary: [
        { word: 'Bank', translation: 'Banco', example: 'The bank is on Main Street.', type: 'noun' },
        { word: 'Hospital', translation: 'Hospital', example: 'She works at a hospital.', type: 'noun' },
        { word: 'Restaurant', translation: 'Restaurante', example: 'Let\'s eat at a restaurant.', type: 'noun' },
        { word: 'Park', translation: 'Parque', example: 'Children play in the park.', type: 'noun' },
        { word: 'Store', translation: 'Tienda', example: 'I buy food at the store.', type: 'noun' },
      ],
      grammar: {
        title: 'Prepositions of Place',
        explanation: 'Use prepositions (in, on, at, next to, near, between) to describe locations.',
        examples: ['The bank is on Main Street.', 'The park is next to the school.', 'I am at home.'],
        rules: [
          'Use "at" for specific locations',
          'Use "on" for streets',
          'Use "in" for cities/countries',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'The restaurant is ___ the bank.',
          options: ['next to', 'next', 'to next', 'near to'],
          correctAnswer: 'next to',
          explanation: 'We use "next to" to show something is beside something else.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'I live ___ New York.',
          correctAnswer: 'in',
          explanation: 'We use "in" for cities.',
        },
      ],
      shadowingText: 'There is a bank on Main Street. The hospital is next to the park. The restaurant is near my house. I go to the store every day.',
    },
  ],
  A2: [
    {
      id: 'a2-1',
      level: 'A2',
      order: 1,
      title: 'Past Simple Tense',
      objective: 'Talk about completed actions in the past',
      vocabulary: [
        { word: 'Yesterday', translation: 'Ayer', example: 'I went to the store yesterday.', type: 'adverb' },
        { word: 'Last week', translation: 'La semana pasada', example: 'Last week was busy.', type: 'phrase' },
        { word: 'Ago', translation: 'Hace', example: 'Two years ago, I moved here.', type: 'adverb' },
        { word: 'Visited', translation: 'Visité', example: 'We visited Paris.', type: 'verb' },
        { word: 'Watched', translation: 'Vi', example: 'I watched a movie.', type: 'verb' },
      ],
      grammar: {
        title: 'Past Simple Formation',
        explanation: 'Use past simple for completed actions. Regular verbs add -ed, irregular verbs change form.',
        examples: ['I walked to school.', 'She went home.', 'They ate dinner.', 'We watched TV.'],
        rules: [
          'Regular verbs: add -ed',
          'Irregular verbs: learn special forms',
          'Use "did" for questions and negatives',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I ___ to the cinema yesterday.',
          options: ['go', 'goes', 'went', 'going'],
          correctAnswer: 'went',
          explanation: '"Went" is the past simple form of "go".',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She ___ a book last night. (read)',
          correctAnswer: 'read',
          explanation: 'The past form of "read" is also "read" (but pronounced differently).',
        },
      ],
      shadowingText: 'Yesterday, I went to the park. I walked for one hour. Then I met my friend. We talked and laughed together.',
    },
    {
      id: 'a2-2',
      level: 'A2',
      order: 2,
      title: 'Making Plans',
      objective: 'Talk about future plans and intentions',
      vocabulary: [
        { word: 'Will', translation: 'Iré/Haré', example: 'I will call you tomorrow.', type: 'verb' },
        { word: 'Going to', translation: 'Voy a', example: 'I am going to study.', type: 'phrase' },
        { word: 'Tomorrow', translation: 'Mañana', example: 'See you tomorrow!', type: 'adverb' },
        { word: 'Next', translation: 'Próximo', example: 'Next week I start work.', type: 'adjective' },
        { word: 'Plan', translation: 'Plan', example: 'What are your plans?', type: 'noun' },
      ],
      grammar: {
        title: 'Future Forms',
        explanation: 'Use "going to" for plans and "will" for decisions and predictions.',
        examples: ['I am going to visit my aunt.', 'I will help you.', 'It will rain tomorrow.'],
        rules: [
          'Be + going to + verb for plans',
          'Will + verb for spontaneous decisions',
          'Both can express future',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I ___ going to study English tonight.',
          options: ['am', 'is', 'are', 'be'],
          correctAnswer: 'am',
          explanation: 'With "I", we use "am" in the "going to" structure.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She ___ call you later. (spontaneous decision)',
          correctAnswer: 'will',
          explanation: 'We use "will" for spontaneous decisions made at the moment of speaking.',
        },
      ],
      shadowingText: 'Tomorrow, I am going to wake up early. I will exercise in the morning. Then I am going to meet my friends for lunch.',
    },
    {
      id: 'a2-3',
      level: 'A2',
      order: 3,
      title: 'Comparatives and Superlatives',
      objective: 'Compare things and describe extremes',
      vocabulary: [
        { word: 'Better', translation: 'Mejor', example: 'This is better than that.', type: 'adjective' },
        { word: 'Worse', translation: 'Peor', example: 'Today is worse than yesterday.', type: 'adjective' },
        { word: 'Bigger', translation: 'Más grande', example: 'This house is bigger.', type: 'adjective' },
        { word: 'Best', translation: 'Mejor', example: 'She is the best student.', type: 'adjective' },
        { word: 'Most', translation: 'Más', example: 'The most expensive car.', type: 'adjective' },
      ],
      grammar: {
        title: 'Forming Comparatives and Superlatives',
        explanation: 'Use comparatives to compare two things and superlatives for the extreme among three or more.',
        examples: ['Bigger than', 'More expensive than', 'The biggest', 'The most expensive'],
        rules: [
          'Short adjectives: add -er/-est',
          'Long adjectives: use more/most',
          'Irregular: good-better-best, bad-worse-worst',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'This book is ___ than that one.',
          options: ['interesting', 'more interesting', 'most interesting', 'interestinger'],
          correctAnswer: 'more interesting',
          explanation: 'For long adjectives like "interesting", we use "more" for the comparative.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She is the ___ student in the class. (good)',
          correctAnswer: 'best',
          explanation: 'The superlative of "good" is "best".',
        },
      ],
      shadowingText: 'My house is bigger than yours. This car is more expensive than that one. She is the best teacher. He is the tallest in the class.',
    },
    {
      id: 'a2-4',
      level: 'A2',
      order: 4,
      title: 'Health and Body',
      objective: 'Discuss health, body parts, and medical issues',
      vocabulary: [
        { word: 'Headache', translation: 'Dolor de cabeza', example: 'I have a headache.', type: 'noun' },
        { word: 'Fever', translation: 'Fiebre', example: 'She has a fever.', type: 'noun' },
        { word: 'Medicine', translation: 'Medicina', example: 'Take this medicine.', type: 'noun' },
        { word: 'Doctor', translation: 'Doctor/a', example: 'I need to see a doctor.', type: 'noun' },
        { word: 'Feel', translation: 'Sentir', example: 'I feel sick.', type: 'verb' },
      ],
      grammar: {
        title: 'Have and Feel',
        explanation: 'Use "have" with illnesses and "feel" with adjectives describing health.',
        examples: ['I have a cold.', 'She has a stomachache.', 'I feel sick.', 'He feels better.'],
        rules: [
          'Have + a/an + illness',
          'Feel + adjective',
          'Should + verb for advice',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I ___ a terrible headache.',
          options: ['am', 'have', 'feel', 'has'],
          correctAnswer: 'have',
          explanation: 'We use "have" when talking about illnesses.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'You should ___ to the doctor.',
          correctAnswer: 'go',
          explanation: 'After "should", we use the base form of the verb.',
        },
      ],
      shadowingText: 'I don\'t feel well today. I have a headache and a sore throat. I should see a doctor. I need to take some medicine and rest.',
    },
    {
      id: 'a2-5',
      level: 'A2',
      order: 5,
      title: 'Travel and Transportation',
      objective: 'Discuss travel plans and modes of transportation',
      vocabulary: [
        { word: 'Flight', translation: 'Vuelo', example: 'My flight is at 3 PM.', type: 'noun' },
        { word: 'Train', translation: 'Tren', example: 'I take the train to work.', type: 'noun' },
        { word: 'Ticket', translation: 'Boleto', example: 'I need to buy a ticket.', type: 'noun' },
        { word: 'Airport', translation: 'Aeropuerto', example: 'We arrived at the airport.', type: 'noun' },
        { word: 'Journey', translation: 'Viaje', example: 'The journey was long.', type: 'noun' },
      ],
      grammar: {
        title: 'Prepositions of Movement',
        explanation: 'Use prepositions (to, from, by, on) to describe travel and transportation.',
        examples: ['I go to school by bus.', 'She came from Paris.', 'Travel on a train.'],
        rules: [
          'Go to + destination',
          'Come from + origin',
          'Travel by + transport method',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I travel to work ___ car.',
          options: ['with', 'by', 'in', 'on'],
          correctAnswer: 'by',
          explanation: 'We use "by" when talking about methods of transportation.',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She goes ___ school every day.',
          correctAnswer: 'to',
          explanation: 'We use "to" to show movement toward a destination.',
        },
      ],
      shadowingText: 'I am going to travel to London next month. I will go by plane. The flight is three hours. I need to buy a ticket and book a hotel.',
    },
    {
      id: 'a2-6',
      level: 'A2',
      order: 6,
      title: 'Hobbies and Interests',
      objective: 'Talk about hobbies, interests, and free time activities',
      vocabulary: [
        { word: 'Hobby', translation: 'Pasatiempo', example: 'Reading is my hobby.', type: 'noun' },
        { word: 'Enjoy', translation: 'Disfrutar', example: 'I enjoy playing guitar.', type: 'verb' },
        { word: 'Free time', translation: 'Tiempo libre', example: 'What do you do in your free time?', type: 'phrase' },
        { word: 'Interested', translation: 'Interesado', example: 'I am interested in art.', type: 'adjective' },
        { word: 'Favorite', translation: 'Favorito', example: 'What is your favorite sport?', type: 'adjective' },
      ],
      grammar: {
        title: 'Gerunds and Infinitives',
        explanation: 'Some verbs are followed by gerunds (-ing), others by infinitives (to + verb).',
        examples: ['I enjoy swimming.', 'I want to learn.', 'She likes reading.', 'He decided to go.'],
        rules: [
          'Enjoy, like, love + gerund',
          'Want, need, decide + infinitive',
          'Some verbs take both',
        ],
      },
      exercises: [
        {
          id: 'ex1',
          type: 'multiple-choice',
          question: 'I enjoy ___ books.',
          options: ['read', 'to read', 'reading', 'reads'],
          correctAnswer: 'reading',
          explanation: 'After "enjoy", we use a gerund (verb + -ing).',
        },
        {
          id: 'ex2',
          type: 'fill-blank',
          question: 'She wants ___ Spanish. (learn)',
          correctAnswer: 'to learn',
          explanation: 'After "want", we use the infinitive (to + verb).',
        },
      ],
      shadowingText: 'I love reading books in my free time. I also enjoy playing tennis and listening to music. My favorite hobby is photography. What do you like doing?',
    },
  ],
  B1: B1_LESSONS,
  B2: B2_LESSONS,
  C1: C1_LESSONS,
  C2: C2_LESSONS,
}

export const PLACEMENT_TEST_QUESTIONS: PlacementTestQuestion[] = [
  {
    id: 'pt-1',
    question: 'Hello! My name ___ Maria.',
    options: ['am', 'is', 'are', 'be'],
    correctAnswer: 'is',
    level: 'Beginner',
    difficultyScore: 1,
  },
  {
    id: 'pt-2',
    question: 'I ___ to the store yesterday.',
    options: ['go', 'goes', 'went', 'going'],
    correctAnswer: 'went',
    level: 'A1',
    difficultyScore: 2,
  },
  {
    id: 'pt-3',
    question: 'She ___ tennis every Sunday.',
    options: ['play', 'plays', 'playing', 'played'],
    correctAnswer: 'plays',
    level: 'A1',
    difficultyScore: 2,
  },
  {
    id: 'pt-4',
    question: 'This book is ___ than that one.',
    options: ['good', 'better', 'best', 'more good'],
    correctAnswer: 'better',
    level: 'A2',
    difficultyScore: 3,
  },
  {
    id: 'pt-5',
    question: 'I ___ to Paris last year.',
    options: ['have been', 'was', 'been', 'am'],
    correctAnswer: 'was',
    level: 'A2',
    difficultyScore: 3,
  },
  {
    id: 'pt-6',
    question: 'If I ___ time, I would travel more.',
    options: ['have', 'had', 'will have', 'would have'],
    correctAnswer: 'had',
    level: 'B1',
    difficultyScore: 4,
  },
  {
    id: 'pt-7',
    question: 'The report ___ by the team yesterday.',
    options: ['completed', 'was completed', 'is completed', 'completes'],
    correctAnswer: 'was completed',
    level: 'B1',
    difficultyScore: 4,
  },
  {
    id: 'pt-8',
    question: 'I wish I ___ more languages.',
    options: ['speak', 'spoke', 'spoken', 'speaking'],
    correctAnswer: 'spoke',
    level: 'B2',
    difficultyScore: 5,
  },
  {
    id: 'pt-9',
    question: 'By next year, I ___ here for ten years.',
    options: ['work', 'worked', 'will have worked', 'have worked'],
    correctAnswer: 'will have worked',
    level: 'B2',
    difficultyScore: 5,
  },
  {
    id: 'pt-10',
    question: 'Had I known about the meeting, I ___ attended.',
    options: ['would have', 'will have', 'had', 'have'],
    correctAnswer: 'would have',
    level: 'C1',
    difficultyScore: 6,
  },
]

export const ACHIEVEMENT_DEFINITIONS: Omit<Achievement, 'unlockedAt'>[] = [
  {
    id: 'first-lesson',
    title: 'First Steps',
    description: 'Complete your first lesson',
    icon: 'Book',
  },
  {
    id: 'week-streak',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: 'Flame',
  },
  {
    id: 'month-streak',
    title: 'Monthly Master',
    description: 'Maintain a 30-day streak',
    icon: 'Fire',
  },
  {
    id: 'level-complete',
    title: 'Level Up!',
    description: 'Complete all lessons in a level',
    icon: 'Trophy',
  },
  {
    id: 'perfect-score',
    title: 'Perfectionist',
    description: 'Score 100% on a lesson',
    icon: 'Star',
  },
  {
    id: 'ten-lessons',
    title: 'Dedicated Learner',
    description: 'Complete 10 lessons',
    icon: 'Target',
  },
  {
    id: 'fifty-lessons',
    title: 'Learning Champion',
    description: 'Complete 50 lessons',
    icon: 'Medal',
  },
]